import { useEffect, useMemo, useState } from 'react';
import { Check, Edit2, FileSpreadsheet, Plus, QrCode, Search, Trash2, Upload, Users, X } from 'lucide-react';
import { adminRequest, api, type DeparturePassenger, type DeparturePassengerData, type PassengerInput } from '../../lib/api';
import WristbandScannerModal from '../admin/WristbandScannerModal';

type Props = { departureId: string; readOnly?: boolean; onBack?: () => void };
type Form = { fullName:string; documentType:string; documentNumber:string; externalNumber:string; email:string; mobile:string; phone:string; country:string; birthDate:string; documentExpiresAt:string; passengerStatus:string; bonus:string };
const emptyForm: Form = { fullName:'', documentType:'DNI', documentNumber:'', externalNumber:'', email:'', mobile:'', phone:'', country:'', birthDate:'', documentExpiresAt:'', passengerStatus:'', bonus:'' };
const input: React.CSSProperties = { width:'100%', height:39, padding:'0 10px', border:'1px solid #DCE3EB', borderRadius:7, boxSizing:'border-box', font:'inherit', background:'#fff' };
const button: React.CSSProperties = { height:36, display:'inline-flex', alignItems:'center', justifyContent:'center', gap:7, padding:'0 12px', border:'1px solid #DCE3EB', borderRadius:7, background:'#fff', color:'#1A4B77', fontSize:13, fontWeight:600, cursor:'pointer' };
const iconButton: React.CSSProperties = { display: 'inline-flex', alignItems: 'center', justifyContent: 'center', width: 30, height: 30, border: 0, background: 'none', cursor: 'pointer', color: '#1A4B77' };
const primary: React.CSSProperties = { ...button, background:'#1A4B77', borderColor:'#1A4B77', color:'#fff' };
const date = (value?:string|null) => value ? value.slice(0,10).split('-').reverse().join('/') : '-';
const toForm = (item: DeparturePassenger): Form => ({ fullName:item.full_name, documentType:item.document_type, documentNumber:item.document_number, externalNumber:item.external_number??'', email:item.email??'', mobile:item.mobile??'', phone:item.phone??'', country:item.country??'', birthDate:item.birth_date?.slice(0,10)??'', documentExpiresAt:item.document_expires_at?.slice(0,10)??'', passengerStatus:item.passenger_status??'', bonus:item.bonus??'' });
const asInput = (form: Form): PassengerInput => ({ fullName:form.fullName, documentType:form.documentType, documentNumber:form.documentNumber, externalNumber:form.externalNumber||null, email:form.email||null, mobile:form.mobile||null, phone:form.phone||null, country:form.country||null, birthDate:form.birthDate||null, documentExpiresAt:form.documentExpiresAt||null, passengerStatus:form.passengerStatus||null, bonus:form.bonus||null });

export default function DeparturePassengers({ departureId, readOnly = false, onBack }: Props) {
  const [data,setData] = useState<DeparturePassengerData|null>(null), [schoolId,setSchoolId] = useState(''), [search,setSearch] = useState(''), [loading,setLoading] = useState(true), [error,setError] = useState(''), [message,setMessage] = useState('');
  const [selectedSchool,setSelectedSchool] = useState(''), [busy,setBusy] = useState(false), [detail,setDetail] = useState<DeparturePassenger|null>(null), [editForm,setEditForm] = useState<Form>(emptyForm), [wristbandTarget,setWristbandTarget] = useState<DeparturePassenger|null>(null);
  const load = async () => { setLoading(true); try { const next = await api.departurePassengers(departureId, { schoolId: schoolId || undefined, q: search || undefined }); setData(next); if (!selectedSchool && next.schools.length) setSelectedSchool(next.schools[0].id); setError(''); } catch (reason) { setError(reason instanceof Error ? reason.message : 'No se pudieron cargar los pasajeros.'); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, [departureId, schoolId, search]);
  const currentSchool = useMemo(() => data?.schools.find(item => item.id === selectedSchool) ?? null, [data, selectedSchool]);
  const departureTotal = useMemo(() => data?.schools.reduce((sum, s) => sum + (Number(s.passenger_count) || 0), 0) ?? 0, [data?.schools]);
  const saveEdit = async () => { if (!detail || !editForm.fullName || !editForm.documentNumber) return; setBusy(true); try { await adminRequest(`/passengers/${detail.id}`, { method:'PATCH', body:JSON.stringify(asInput(editForm)) }); setDetail(null); setMessage('Datos del pasajero actualizados.'); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : 'No se pudo actualizar el pasajero.'); } finally { setBusy(false); } };
  if (loading && !data) return <div style={{padding:36,color:'#64748B'}}>Cargando pasajeros de la salida…</div>;
  if (!data) return <div style={{padding:36,color:'#B91C1C'}}>{error || 'No se pudo cargar la salida.'}</div>;
  const departureLabel = `${data.departure.type === 'MICRO' ? 'Micro' : 'Aéreo'} · ${data.departure.name}`;
  return <div style={{flex:1,overflowY:'auto',padding:32}}>
    <div style={{display:'flex',alignItems:'flex-start',justifyContent:'space-between',gap:18,flexWrap:'wrap',marginBottom:22}}><div style={{display:'flex',alignItems:'flex-start',gap:10}}>{onBack&&<button onClick={onBack} title="Volver a salidas" style={{...button,width:36,padding:0}}>←</button>}<div><h2 style={{margin:0,color:'#1A4B77',fontSize:25}}>Pasajeros · {departureLabel}</h2><p style={{margin:'5px 0 0',color:'#64748B',fontSize:14}}>{data.departure.destination} · {date(data.departure.start_date)} al {date(data.departure.end_date)} · <strong>{departureTotal}</strong> pasajeros confirmados</p></div></div></div>
    {message&&<div style={{marginBottom:14,padding:'10px 12px',border:'1px solid #BBF7D0',borderRadius:8,color:'#166534',background:'#F0FDF4',fontSize:13}}>{message}</div>}{error&&<div style={{marginBottom:14,padding:'10px 12px',border:'1px solid #FECACA',borderRadius:8,color:'#B91C1C',background:'#FEF2F2',fontSize:13}}>{error}</div>}
    <div style={{display:'flex',gap:8,flexWrap:'wrap',marginBottom:18}}><button onClick={()=>setSchoolId('')} style={{...button,background:!schoolId?'#1A4B77':'#fff',borderColor:!schoolId?'#1A4B77':'#DCE3EB',color:!schoolId?'#fff':'#1A4B77'}}>Toda la salida <span style={{opacity:.8}}>({departureTotal})</span></button>{data.schools.map(school=><button key={school.id} onClick={()=>{setSchoolId(school.id);setSelectedSchool(school.id);}} style={{...button,background:schoolId===school.id?'#1A4B77':'#fff',borderColor:schoolId===school.id?'#1A4B77':'#DCE3EB',color:schoolId===school.id?'#fff':'#1A4B77'}}>{school.name} ({school.code}) <span style={{opacity:.8}}>({school.passenger_count})</span></button>)}</div>
    {!data.schools.length&&<div style={{padding:18,border:'1px solid #FDE68A',borderRadius:8,background:'#FFFBEB',color:'#92400E',fontSize:13}}>Esta salida todavía no tiene colegios participantes. Asignalos desde “Gestionar salida” antes de cargar pasajeros.</div>}
    <div style={{display:'flex',justifyContent:'space-between',gap:12,alignItems:'center',flexWrap:'wrap',marginBottom:14}}><div style={{position:'relative'}}><Search size={16} style={{position:'absolute',left:11,top:11,color:'#94A3B8'}}/><input value={search} onChange={event=>setSearch(event.target.value)} placeholder="Buscar nombre, documento o nro. externo…" style={{...input,width:310,paddingLeft:34}}/></div><span style={{fontSize:13,color:'#64748B'}}>{schoolId ? `${data.total} pasajero(s) del colegio` : `${data.total} pasajero(s) de la salida`}</span></div>
    <div style={{overflowX:'auto'}}><table style={{width:'100%',minWidth:900,borderCollapse:'collapse'}}><thead><tr style={{borderBottom:'1px solid #DCE3EB'}}>{['Pasajero','Colegio','Documento','Contacto','Pulsera','Estado','Acciones'].map(value=><th key={value} style={{padding:'11px 13px',textAlign:'left',fontSize:12,color:'#64748B',textTransform:'uppercase'}}>{value}</th>)}</tr></thead><tbody>{data.items.map(item=><tr key={item.id} style={{borderBottom:'1px solid #EAF0F5',opacity:item.active?1:.62}}><td style={td}><button onClick={()=>{setDetail(item);setEditForm(toForm(item));}} style={{border:0,background:'none',padding:0,color:'#1A4B77',font: 'inherit',fontWeight:700,cursor:'pointer',textAlign:'left'}}>{item.full_name}</button>{item.external_number&&<div style={{fontSize:12,color:'#64748B'}}>Nro. {item.external_number}</div>}</td><td style={td}><strong>{item.school_code}</strong><div style={{fontSize:12,color:'#64748B'}}>{item.school_name}</div></td><td style={td}>{item.document_type} {item.document_number}</td><td style={td}><div>{item.email||'-'}</div><small style={{color:'#64748B'}}>{item.mobile||item.phone||''}</small></td><td style={td}>{item.wristband_code?<span style={{display:'inline-flex',alignItems:'center',gap:4,padding:'3px 9px',background:'#DCFCE7',borderRadius:12,color:'#15803D',fontSize:12,fontWeight:700}}><QrCode size={12}/>{item.wristband_code}</span>:<span style={{color:'#94A3B8',fontSize:12}}>Sin pulsera</span>}</td><td style={td}>{item.active?'Activo':'Inactivo'}</td><td style={td}>{!readOnly&&<button onClick={()=>setWristbandTarget(item)} style={{...iconButton,color:item.wristband_code?'#15803D':'#1A4B77'}} title={item.wristband_code?'Gestionar pulsera':'Vincular pulsera'}><QrCode size={16}/></button>}</td></tr>)}{!data.items.length&&<tr><td colSpan={7} style={{padding:40,textAlign:'center',color:'#94A3B8'}}>No hay pasajeros confirmados para este filtro.</td></tr>}</tbody></table></div>

    {detail&&<Modal title={detail.full_name} onClose={()=>setDetail(null)}><PassengerFields form={editForm} setForm={setEditForm} readOnly={readOnly}/>{!readOnly&&<Actions onCancel={()=>setDetail(null)} onSave={saveEdit} busy={busy} disabled={!editForm.fullName||!editForm.documentNumber}/>}</Modal>}
    {wristbandTarget&&<WristbandScannerModal passenger={wristbandTarget} onClose={()=>setWristbandTarget(null)} onLinked={code=>{if(data)setData({...data,items:data.items.map(p=>p.id===wristbandTarget.id?{...p,wristband_code:code}:p)});setWristbandTarget(null);}} onUnlinked={()=>{if(data)setData({...data,items:data.items.map(p=>p.id===wristbandTarget.id?{...p,wristband_code:null}:p)});setWristbandTarget(null);}}/>}
  </div>;
}
function SchoolSelect({schools,value,onChange}:{schools:{id:string;name:string;code:string}[];value:string;onChange:(value:string)=>void}) { return <label style={{display:'grid',gap:6,fontSize:13,fontWeight:650,color:'#334155',marginBottom:14}}>Colegio participante<select value={value} onChange={event=>onChange(event.target.value)} style={input}>{schools.map(item=><option key={item.id} value={item.id}>{item.name} ({item.code})</option>)}</select></label>; }
function PassengerFields({form,setForm,readOnly=false}:{form:Form;setForm:(value:Form)=>void;readOnly?:boolean}) { const field=(label:string,key:keyof Form,type='text')=><label style={{display:'grid',gap:6,fontSize:13,color:'#334155'}}>{label}<input disabled={readOnly} type={type} value={form[key]} onChange={event=>setForm({...form,[key]:event.target.value})} style={{...input,background:readOnly?'#F8FAFC':'#fff'}}/></label>; return <div style={{display:'grid',gridTemplateColumns:'repeat(2,minmax(0,1fr))',gap:12}}>{field('Nombre completo','fullName')}{field('Nro. externo','externalNumber')}{field('Tipo de documento','documentType')}{field('Número de documento','documentNumber')}{field('Correo electrónico','email','email')}{field('Celular','mobile')}{field('Teléfono','phone')}{field('País','country')}{field('Fecha de nacimiento','birthDate','date')}{field('Vencimiento documento','documentExpiresAt','date')}{field('Estado','passengerStatus')}{field('Bonificación','bonus')}</div>; }
function Actions({onCancel,onSave,busy,disabled,label='Guardar'}:{onCancel:()=>void;onSave:()=>void;busy:boolean;disabled?:boolean;label?:string}) { return <div style={{display:'flex',justifyContent:'flex-end',gap:9,marginTop:22}}><button style={button} onClick={onCancel}>Cancelar</button><button style={{...primary,opacity:busy||disabled?.6:1}} disabled={busy||disabled} onClick={onSave}><Check size={15}/>{busy?'Procesando…':label}</button></div>; }
function Modal({title,onClose,children}:{title:string;onClose:()=>void;children:React.ReactNode}) { return <div style={{position:'fixed',inset:0,zIndex:100,display:'grid',placeItems:'center',padding:18,background:'rgba(15,23,42,.48)'}}><div style={{width:'min(100%,720px)',maxHeight:'90vh',overflowY:'auto',background:'#fff',borderRadius:12,padding:25,boxShadow:'0 20px 55px rgba(0,0,0,.28)'}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginBottom:20}}><h3 style={{margin:0,color:'#1A4B77',fontSize:21}}>{title}</h3><button onClick={onClose} style={{border:0,background:'none',color:'#64748B',cursor:'pointer'}}><X size={20}/></button></div>{children}</div></div>; }
const td: React.CSSProperties = {padding:'13px',fontSize:13,verticalAlign:'middle'};