# Etapa 1: Construcción (Build)
FROM node:20-alpine AS builder

WORKDIR /app

COPY package*.json ./
RUN npm ci --legacy-peer-deps

COPY . .
RUN npm run build

# Etapa 2: Servidor Web Liviano (Nginx)
FROM nginx:alpine

# Copiamos el build compilado de la etapa 1 al directorio de Nginx
COPY --from=builder /app/dist /usr/share/nginx/html

# Copiamos la configuración de Nginx
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
