import crypto from 'node:crypto';
import { spawn } from 'node:child_process';
import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import sharp from 'sharp';
import { transaction } from './db.js';
import { paths } from './config.js';
import { getStorage } from './storage.js';

const watermarkPath = fileURLToPath(new URL('./assets/marca_agua.png', import.meta.url));
const MAX_ATTEMPTS = 3;
let running = false;
let timer: NodeJS.Timeout | undefined;
type Job = { id:string; attempts:number; media_asset_id:string; drive_file_id:string; mime_type:string; original_name:string; kind:'IMAGE'|'VIDEO'; version_number:number; departure_folder:string; lot_folder:string; };
const safeName=(value:string)=>value.normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-zA-Z0-9._-]+/g,'-').replace(/-+/g,'-').replace(/^[-.]+|[-.]+$/g,'') || 'archivo';
const outputName=(name:string,extension:string)=>safeName(name).replace(/\.[^.]+$/,'')+'-recrear.'+extension;
const tempFile=(suffix:string)=>path.join(paths.uploads,'watermark-'+crypto.randomUUID()+suffix);
function runFfmpeg(input:string,output:string){const filter="[1:v][0:v]scale2ref=w='min(220,max(72,main_w*0.12))':h=-1[wm][base];[base][wm]overlay=x=W-w-W*0.025:y=H-h-H*0.025";return new Promise<void>((resolve,reject)=>{const child=spawn('ffmpeg',['-y','-i',input,'-i',watermarkPath,'-filter_complex',filter,'-map','0:v:0','-map','0:a?','-c:v','libx264','-crf','18','-preset','medium','-c:a','aac','-movflags','+faststart',output],{stdio:['ignore','ignore','pipe']});let error='';child.stderr.on('data',chunk=>{error+=String(chunk);});child.on('error',reject);child.on('close',code=>code===0?resolve():reject(new Error('FFmpeg no pudo crear el video marcado ('+code+'): '+error.slice(-500))));});}
async function watermarkImage(input:string,mime:string){const normalized=sharp(input).rotate();const metadata=await normalized.metadata();const width=metadata.width,height=metadata.height;if(!width||!height)throw new Error('No se pudieron leer las dimensiones de la imagen');const watermarkWidth=Math.max(72,Math.min(220,Math.round(width*.12)));const mark=await sharp(watermarkPath).resize({width:watermarkWidth,withoutEnlargement:true}).png().toBuffer();const markMeta=await sharp(mark).metadata();const margin=Math.max(8,Math.round(width*.025));const target=tempFile(mime==='image/png'?'.png':'.jpg');const composed=sharp(input).rotate().composite([{input:mark,left:Math.max(0,width-(markMeta.width??watermarkWidth)-margin),top:Math.max(0,height-(markMeta.height??watermarkWidth)-margin)}]);if(mime==='image/png')await composed.png({compressionLevel:9}).toFile(target);else await composed.jpeg({quality:92,chromaSubsampling:'4:4:4'}).toFile(target);return {path:target,mimeType:mime==='image/png'?'image/png':'image/jpeg',name:outputName(path.basename(input),mime==='image/png'?'png':'jpg')};}
async function claim():Promise<Job|undefined>{return transaction(async client=>{const result=await client.query<Job>("WITH next AS (SELECT id FROM media_watermark_jobs WHERE status='QUEUED' AND available_at <= now() ORDER BY created_at LIMIT 1 FOR UPDATE SKIP LOCKED) UPDATE media_watermark_jobs j SET status='PROCESSING',started_at=now(),attempts=j.attempts+1,updated_at=now() FROM next JOIN media_assets m ON m.id=j.media_asset_id JOIN lot_versions v ON v.id=m.lot_version_id JOIN lots l ON l.id=v.lot_id JOIN departures d ON d.id=l.departure_id WHERE j.id=next.id RETURNING j.id,j.attempts,j.media_asset_id,m.drive_file_id,m.mime_type,m.original_name,m.kind,v.version_number,regexp_replace(concat_ws(' - ',d.public_code,d.name,d.destination),'[\\/:*?\"<>|]+','-','g') departure_folder,regexp_replace(concat_ws(' - ',l.event_date::text,COALESCE((SELECT name FROM activities WHERE id=l.activity_id),'General'),left(l.id::text,8)),'[\\/:*?\"<>|]+','-','g') lot_folder");return result.rows[0];});}
async function complete(job:Job,delivery:{fileId:string;mimeType:string;size:number;name:string}){await transaction(async client=>{await client.query("UPDATE media_assets SET delivery_drive_file_id=$1,delivery_mime_type=$2,delivery_size_bytes=$3,delivery_name=$4,watermark_status='READY',watermark_error=NULL,status='READY',watermark_attempts=$5 WHERE id=$6",[delivery.fileId,delivery.mimeType,delivery.size,delivery.name,job.attempts,job.media_asset_id]);await client.query("UPDATE media_watermark_jobs SET status='DONE',completed_at=now(),error=NULL,updated_at=now() WHERE id=$1",[job.id]);await client.query("UPDATE lot_versions v SET status='PENDING',submitted_at=COALESCE(submitted_at,now()) WHERE v.id=(SELECT lot_version_id FROM media_assets WHERE id=$1) AND v.status='UPLOADING' AND EXISTS(SELECT 1 FROM media_assets WHERE lot_version_id=v.id) AND NOT EXISTS(SELECT 1 FROM media_assets WHERE lot_version_id=v.id AND status<>'READY')",[job.media_asset_id]);});}
async function failed(job:Job,error:unknown){const message=error instanceof Error?error.message:'No se pudo procesar la marca de agua';const last=job.attempts>=MAX_ATTEMPTS;await transaction(async client=>{await client.query('UPDATE media_assets SET watermark_status=$1,watermark_error=$2,watermark_attempts=$3,status=$4 WHERE id=$5',[last?'FAILED':'PENDING',message,job.attempts,last?'ERROR':'UPLOADING',job.media_asset_id]);await client.query("UPDATE media_watermark_jobs SET status=$1,error=$2,available_at=now()+($3::int * interval '30 seconds'),updated_at=now() WHERE id=$4",[last?'FAILED':'QUEUED',message,job.attempts,job.id]);});}
export async function processNextWatermarkJob(){if(running)return;running=true;let job:Job|undefined;let input='',output='';try{job=await claim();if(!job)return;input=tempFile(job.kind==='VIDEO'?'.source':path.extname(job.original_name)||'.source');await getStorage().download(job.drive_file_id,input);let rendered:{path:string;mimeType:string;name:string};if(job.kind==='VIDEO'){output=tempFile('.mp4');await runFfmpeg(input,output);rendered={path:output,mimeType:'video/mp4',name:outputName(job.original_name,'mp4')};}else{rendered=await watermarkImage(input,job.mime_type);output=rendered.path;rendered.name=outputName(job.original_name,rendered.mimeType==='image/png'?'png':'jpg');}const folder=await getStorage().createVersionFolder({departureFolder:job.departure_folder,lotFolder:job.lot_folder,version:job.version_number},'marcados');const fileId=await getStorage().uploadOriginal({path:rendered.path,filename:rendered.name,mimeType:rendered.mimeType,parentId:folder});const stat=await fs.stat(rendered.path);await complete(job,{fileId,mimeType:rendered.mimeType,size:stat.size,name:rendered.name});}catch(error){if(job)await failed(job,error);else console.error('Watermark worker error',error);}finally{await Promise.all([input,output].filter(Boolean).map(file=>fs.rm(file,{force:true}).catch(()=>undefined)));running=false;}}
export function startWatermarkWorker(){if(timer)return;timer=setInterval(()=>void processNextWatermarkJob(),2000);void processNextWatermarkJob();}
export function stopWatermarkWorker(){if(timer)clearInterval(timer);timer=undefined;}
export async function retryWatermark(mediaId:string){await transaction(async client=>{const media=await client.query('SELECT drive_file_id FROM media_assets WHERE id=$1 FOR UPDATE',[mediaId]);if(!media.rowCount||!media.rows[0].drive_file_id)throw new Error('No se encontro el original para reprocesar');await client.query("UPDATE media_assets SET status='UPLOADING',watermark_status='PENDING',watermark_error=NULL WHERE id=$1",[mediaId]);await client.query("INSERT INTO media_watermark_jobs(media_asset_id,status,attempts,available_at,error,started_at,completed_at) VALUES($1,'QUEUED',0,now(),NULL,NULL,NULL) ON CONFLICT(media_asset_id) DO UPDATE SET status='QUEUED',attempts=0,available_at=now(),error=NULL,started_at=NULL,completed_at=NULL,updated_at=now()",[mediaId]);});}
