import crypto from 'node:crypto';
import { createRequire } from 'node:module';
import { Router, type Request, type Response } from 'express';
import { z } from 'zod';
import { query } from '../db.js';
import { AppError } from '../errors.js';
import { asyncHandler } from '../http.js';
import { getStorage } from '../storage.js';

const require=createRequire(import.meta.url);
const createArchive=require('archiver') as (format:string,options:{zlib:{level:number}})=>{on(event:string,callback:(error:Error)=>void):void;pipe(destination:NodeJS.WritableStream):void;append(source:NodeJS.ReadableStream,options:{name:string}):void;finalize():Promise<void>;};
const tokenSchema=z.string().regex(/^[A-Za-z0-9_-]{32,128}$/); const idSchema=z.string().uuid(); const codeSchema=z.string().min(3).max(48).regex(/^[A-Za-z0-9_-]+$/);
const param=(value:string|string[])=>Array.isArray(value)?value[0]:value; const hashToken=(token:string)=>crypto.createHash('sha256').update(token).digest('hex');
type PublicLink={school_id:string;school_name:string}; type PublicMedia={id:string;drive_file_id:string;delivery_drive_file_id:string|null;thumbnail_drive_file_id:string|null;original_name:string;delivery_name:string|null;mime_type:string;delivery_mime_type:string|null;size_bytes:number;delivery_size_bytes:number|null;kind:'IMAGE'|'VIDEO';departure_id:string}; type PublicDeparture={id:string;public_code:string;name:string;destination:string;type:'MICRO'|'AEREO';event_date:string;start_date:string;end_date:string};
const deliveryId=(media:PublicMedia)=>media.delivery_drive_file_id??media.drive_file_id; const deliveryMime=(media:PublicMedia)=>media.delivery_mime_type??media.mime_type; const deliverySize=(media:PublicMedia)=>media.delivery_size_bytes??media.size_bytes; const deliveryName=(media:PublicMedia)=>media.delivery_name??media.original_name;
function secureHeaders(res:Response){res.setHeader('Cache-Control','private, no-store, max-age=0');res.setHeader('X-Robots-Tag','noindex, nofollow, noarchive');res.setHeader('Referrer-Policy','no-referrer');}
async function resolveLink(rawToken:string):Promise<PublicLink>{const result=await query<PublicLink>('SELECT p.school_id,s.name school_name FROM public_school_links p JOIN schools s ON s.id=p.school_id WHERE p.token_hash=$1 AND p.active AND s.active AND s.deleted_at IS NULL',[hashToken(tokenSchema.parse(rawToken))]);if(!result.rowCount)throw new AppError(404,'PUBLIC_LINK_NOT_FOUND','El enlace no es válido o fue revocado');return result.rows[0];}
async function resolveDeparture(rawCode:string):Promise<PublicDeparture>{const result=await query<PublicDeparture>('SELECT id,public_code,name,destination,type,event_date::text,start_date::text,end_date::text FROM departures WHERE lower(public_code)=lower($1) AND public_access_active',[codeSchema.parse(rawCode)]);if(!result.rowCount)throw new AppError(404,'PUBLIC_DEPARTURE_NOT_FOUND','La salida no está disponible');return result.rows[0];}

// Un álbum acumula todas sus revisiones PUBLISHED; current_published_version_id solo marca la última.
const lotSummary=`SELECT l.id,l.event_date,l.title,d.id departure_id,d.name departure_name,d.destination departure_destination,d.type departure_type,d.name school_name,COALESCE(NULLIF(l.title,''),a.name,'General') activity_name,
  latest.id version_id,latest.version_number,latest.status,
  COUNT(m.id) FILTER(WHERE m.status='APPROVED')::int approved_count,
  COALESCE((SELECT json_agg(row_to_json(cover)) FROM (SELECT ma.id,ma.kind,ma.status,COALESCE(ma.delivery_name,ma.original_name) original_name,COALESCE(ma.delivery_mime_type,ma.mime_type) mime_type,COALESCE(ma.delivery_size_bytes,ma.size_bytes) size_bytes FROM media_assets ma JOIN lot_versions pv ON pv.id=ma.lot_version_id WHERE pv.lot_id=l.id AND pv.status='PUBLISHED' AND ma.status='APPROVED' ORDER BY ma.created_at DESC LIMIT 3) cover),'[]'::json) cover_media
  FROM lots l JOIN departures d ON d.id=l.departure_id LEFT JOIN activities a ON a.id=l.activity_id
  JOIN lot_versions published ON published.lot_id=l.id AND published.status='PUBLISHED'
  LEFT JOIN media_assets m ON m.lot_version_id=published.id
  JOIN LATERAL (SELECT id,version_number,status FROM lot_versions WHERE lot_id=l.id AND status='PUBLISHED' ORDER BY reviewed_at DESC NULLS LAST,created_at DESC LIMIT 1) latest ON true`;
const lotGroup=' GROUP BY l.id,d.id,a.id,latest.id,latest.version_number,latest.status';
async function publishedLot(lotId:string,schoolId?:string,departureId?:string){const schoolJoin=schoolId?' JOIN departure_schools ds ON ds.departure_id=d.id AND ds.school_id=$2':'';const scope=schoolId?'l.id=$1': 'l.id=$1 AND l.departure_id=$2';const values=schoolId?[lotId,schoolId]:[lotId,departureId];const result=await query(`${lotSummary}${schoolJoin} WHERE ${scope} AND l.deleted_at IS NULL${lotGroup}`,values);if(!result.rowCount)throw new AppError(404,'PUBLIC_LOT_NOT_FOUND','El álbum publicado no existe');return result.rows[0];}
async function publicMedia(mediaId:string,schoolId?:string,departureId?:string):Promise<PublicMedia>{const access=schoolId?'JOIN departure_schools ds ON ds.departure_id=l.departure_id AND ds.school_id=$2':'JOIN departures d ON d.id=l.departure_id AND d.public_access_active';const scope=schoolId?'':' AND l.departure_id=$2';const values=schoolId?[mediaId,schoolId]:[mediaId,departureId];const result=await query<PublicMedia>(`SELECT m.id,m.drive_file_id,m.delivery_drive_file_id,m.thumbnail_drive_file_id,m.original_name,m.delivery_name,m.mime_type,m.delivery_mime_type,m.size_bytes,m.delivery_size_bytes,m.kind,l.departure_id FROM media_assets m JOIN lot_versions v ON v.id=m.lot_version_id JOIN lots l ON l.id=v.lot_id ${access} WHERE m.id=$1 AND v.status='PUBLISHED' AND m.status='APPROVED'${scope}`,values);if(!result.rowCount||!deliveryId(result.rows[0]))throw new AppError(404,'PUBLIC_MEDIA_NOT_FOUND','El archivo publicado no existe');return result.rows[0];}
async function stream(req:Request,res:Response,media:PublicMedia,attachment=false,thumbnail=false){const targetId=thumbnail&&media.thumbnail_drive_file_id?media.thumbnail_drive_file_id:deliveryId(media);const storage=getStorage();if(!req.headers.range&&storage.signedUrl&&media.kind!=='VIDEO')return res.redirect(302,await storage.signedUrl(targetId,attachment));const remote=await storage.stream(targetId,req.headers.range);res.status(remote.status).setHeader('Content-Type',remote.mimeType||deliveryMime(media)).setHeader('Accept-Ranges','bytes');if(remote.size!==undefined)res.setHeader('Content-Length',String(remote.size));if(remote.contentRange)res.setHeader('Content-Range',remote.contentRange);if(attachment)res.setHeader('Content-Disposition',`attachment; filename*=UTF-8''${encodeURIComponent(deliveryName(media))}`);remote.stream.pipe(res);}
async function zip(res:Response,items:PublicMedia[],name:string){res.setHeader('Content-Type','application/zip');res.setHeader('Content-Disposition',`attachment; filename="${name}.zip"`);const archive=createArchive('zip',{zlib:{level:6}});archive.on('error',error=>res.destroy(error));archive.pipe(res);for(const item of items){const remote=await getStorage().stream(deliveryId(item));archive.append(remote.stream,{name:deliveryName(item)});}await archive.finalize();}
async function lotMedia(lotId:string){return query(`SELECT m.id,m.kind,m.status,COALESCE(m.delivery_name,m.original_name) original_name,COALESCE(m.delivery_mime_type,m.mime_type) mime_type,COALESCE(m.delivery_size_bytes,m.size_bytes) size_bytes FROM media_assets m JOIN lot_versions v ON v.id=m.lot_version_id WHERE v.lot_id=$1 AND v.status='PUBLISHED' AND m.status='APPROVED' ORDER BY m.sort_order,m.created_at`,[lotId]);}

export const publicRouter=Router(); publicRouter.use((_,res,next)=>{secureHeaders(res);next();});
publicRouter.get('/departures/:code',asyncHandler(async(req,res)=>{const departure=await resolveDeparture(param(req.params.code));const items=await query(`${lotSummary} WHERE l.departure_id=$1 AND l.deleted_at IS NULL${lotGroup} ORDER BY l.event_date DESC,latest.version_number DESC`,[departure.id]);res.json({departure,items:items.rows});}));
publicRouter.get('/departures/:code/lots/:lotId',asyncHandler(async(req,res)=>{const departure=await resolveDeparture(param(req.params.code));const lot=await publishedLot(idSchema.parse(param(req.params.lotId)),undefined,departure.id);const media=await lotMedia(lot.id);res.json({lot,media:media.rows});}));
for(const [suffix,attachment] of [['content',false],['thumbnail',false],['download',true]] as const) publicRouter.get(`/departures/:code/media/:mediaId/${suffix}`,asyncHandler(async(req,res)=>{const departure=await resolveDeparture(param(req.params.code));await stream(req,res,await publicMedia(idSchema.parse(param(req.params.mediaId)),undefined,departure.id),attachment,suffix==='thumbnail');}));
publicRouter.post('/departures/:code/downloads/zip',asyncHandler(async(req,res)=>{const departure=await resolveDeparture(param(req.params.code));const input=z.object({mediaIds:z.array(z.string().uuid()).min(1).max(100)}).parse(req.body);await zip(res,await Promise.all(input.mediaIds.map(id=>publicMedia(id,undefined,departure.id))),departure.public_code+'-galeria');}));
publicRouter.get('/:token',asyncHandler(async(req,res)=>{const link=await resolveLink(param(req.params.token));const items=await query(`${lotSummary} JOIN departure_schools ds ON ds.departure_id=d.id AND ds.school_id=$1 WHERE l.deleted_at IS NULL${lotGroup} ORDER BY l.event_date DESC,latest.version_number DESC`,[link.school_id]);res.json({school:{id:link.school_id,name:link.school_name},items:items.rows});}));
publicRouter.get('/:token/lots/:lotId',asyncHandler(async(req,res)=>{const link=await resolveLink(param(req.params.token));const lot=await publishedLot(idSchema.parse(param(req.params.lotId)),link.school_id);const media=await lotMedia(lot.id);res.json({lot,media:media.rows});}));
for(const [suffix,attachment] of [['content',false],['thumbnail',false],['download',true]] as const) publicRouter.get(`/:token/media/:mediaId/${suffix}`,asyncHandler(async(req,res)=>{const link=await resolveLink(param(req.params.token));await stream(req,res,await publicMedia(idSchema.parse(param(req.params.mediaId)),link.school_id),attachment,suffix==='thumbnail');}));
publicRouter.post('/:token/downloads/zip',asyncHandler(async(req,res)=>{const link=await resolveLink(param(req.params.token));const input=z.object({mediaIds:z.array(z.string().uuid()).min(1).max(100)}).parse(req.body);await zip(res,await Promise.all(input.mediaIds.map(id=>publicMedia(id,link.school_id))),'galeria-recrear');}));
