import crypto from 'node:crypto';
import { createRequire } from 'node:module';
import { Router, type Request, type Response } from 'express';
import { z } from 'zod';
import { query } from '../db.js';
import { AppError } from '../errors.js';
import { asyncHandler } from '../http.js';
import { getStorage } from '../storage.js';

const require=createRequire(import.meta.url);
const createArchive=require('archiver') as (format:string,options:{zlib:{level:number}})=>{on(event:string,callback:(error:Error)=>void):void;pipe(destination:NodeJS.WritableStream):void;append(source:NodeJS.ReadableStream,options:{name:string}):void;finalize():Promise<void>;};
const tokenSchema=z.string().regex(/^[A-Za-z0-9_-]{32,128}$/);const idSchema=z.string().uuid();const codeSchema=z.string().min(3).max(48).regex(/^[A-Za-z0-9_-]+$/);const param=(value:string|string[])=>Array.isArray(value)?value[0]:value;const hashToken=(token:string)=>crypto.createHash('sha256').update(token).digest('hex');
type PublicLink={school_id:string;school_name:string};
type PublicMedia={id:string;drive_file_id:string;delivery_drive_file_id:string|null;original_name:string;delivery_name:string|null;mime_type:string;delivery_mime_type:string|null;size_bytes:number;delivery_size_bytes:number|null;kind:'IMAGE'|'VIDEO';departure_id:string};
const deliveryId=(media:PublicMedia)=>media.delivery_drive_file_id??media.drive_file_id;const deliveryMime=(media:PublicMedia)=>media.delivery_mime_type??media.mime_type;const deliverySize=(media:PublicMedia)=>media.delivery_size_bytes??media.size_bytes;const deliveryName=(media:PublicMedia)=>media.delivery_name??media.original_name;
type PublicDeparture={id:string;public_code:string;name:string;destination:string;type:'MICRO'|'AEREO';event_date:string;start_date:string;end_date:string};
function secureHeaders(res:Response){res.setHeader('Cache-Control','private, no-store, max-age=0');res.setHeader('X-Robots-Tag','noindex, nofollow, noarchive');res.setHeader('Referrer-Policy','no-referrer');}
async function resolveLink(rawToken:string):Promise<PublicLink>{const token=tokenSchema.parse(rawToken);const result=await query<PublicLink>(`SELECT p.school_id,s.name school_name FROM public_school_links p JOIN schools s ON s.id=p.school_id WHERE p.token_hash=$1 AND p.active AND s.active AND s.deleted_at IS NULL`,[hashToken(token)]);if(!result.rowCount)throw new AppError(404,'PUBLIC_LINK_NOT_FOUND','El enlace no es válido o fue revocado');return result.rows[0];}
async function resolveDeparture(rawCode:string):Promise<PublicDeparture>{const code=codeSchema.parse(rawCode);const result=await query<PublicDeparture>(`SELECT id,public_code,name,destination,type,event_date::text,start_date::text,end_date::text FROM departures WHERE lower(public_code)=lower($1) AND public_access_active`,[code]);if(!result.rowCount)throw new AppError(404,'PUBLIC_DEPARTURE_NOT_FOUND','La salida no está disponible');return result.rows[0];}
async function publishedLot(schoolId:string,lotId:string){const result=await query(`SELECT l.id,l.event_date,l.title,d.id departure_id,d.name departure_name,d.destination departure_destination,d.type departure_type,d.name school_name,COALESCE(NULLIF(l.title,''),a.name,'General') activity_name,v.id version_id,v.version_number,v.status,COUNT(m.id) FILTER(WHERE m.status='APPROVED')::int approved_count FROM lots l JOIN departures d ON d.id=l.departure_id JOIN departure_schools ds ON ds.departure_id=d.id AND ds.school_id=$2 JOIN lot_versions v ON v.id=l.current_published_version_id AND v.status='PUBLISHED' LEFT JOIN activities a ON a.id=l.activity_id LEFT JOIN media_assets m ON m.lot_version_id=v.id WHERE l.id=$1 GROUP BY l.id,d.id,a.id,v.id`,[lotId,schoolId]);if(!result.rowCount)throw new AppError(404,'PUBLIC_LOT_NOT_FOUND','El lote publicado no existe');return result.rows[0];}
async function publishedDepartureLot(departureId:string,lotId:string){const result=await query(`SELECT l.id,l.event_date,l.title,d.id departure_id,d.name departure_name,d.destination departure_destination,d.type departure_type,d.name school_name,COALESCE(NULLIF(l.title,''),a.name,'General') activity_name,v.id version_id,v.version_number,v.status,COUNT(m.id) FILTER(WHERE m.status='APPROVED')::int approved_count FROM lots l JOIN departures d ON d.id=l.departure_id JOIN lot_versions v ON v.id=l.current_published_version_id AND v.status='PUBLISHED' LEFT JOIN activities a ON a.id=l.activity_id LEFT JOIN media_assets m ON m.lot_version_id=v.id WHERE l.id=$1 AND l.departure_id=$2 GROUP BY l.id,d.id,a.id,v.id`,[lotId,departureId]);if(!result.rowCount)throw new AppError(404,'PUBLIC_LOT_NOT_FOUND','El lote publicado no existe');return result.rows[0];}
async function publicMedia(schoolId:string,mediaId:string):Promise<PublicMedia>{const result=await query<PublicMedia>(`SELECT m.id,m.drive_file_id,m.delivery_drive_file_id,m.original_name,m.delivery_name,m.mime_type,m.delivery_mime_type,m.size_bytes,m.delivery_size_bytes,m.kind,l.departure_id FROM media_assets m JOIN lot_versions v ON v.id=m.lot_version_id JOIN lots l ON l.id=v.lot_id JOIN departure_schools ds ON ds.departure_id=l.departure_id AND ds.school_id=$2 WHERE m.id=$1 AND l.current_published_version_id=m.lot_version_id AND v.status='PUBLISHED' AND m.status='APPROVED'`,[mediaId,schoolId]);if(!result.rowCount||!deliveryId(result.rows[0]))throw new AppError(404,'PUBLIC_MEDIA_NOT_FOUND','El archivo publicado no existe');return result.rows[0];}
async function departureMedia(departureId:string,mediaId:string):Promise<PublicMedia>{const result=await query<PublicMedia>(`SELECT m.id,m.drive_file_id,m.delivery_drive_file_id,m.original_name,m.delivery_name,m.mime_type,m.delivery_mime_type,m.size_bytes,m.delivery_size_bytes,m.kind,l.departure_id FROM media_assets m JOIN lot_versions v ON v.id=m.lot_version_id JOIN lots l ON l.id=v.lot_id JOIN departures d ON d.id=l.departure_id WHERE m.id=$1 AND l.departure_id=$2 AND d.public_access_active AND l.current_published_version_id=m.lot_version_id AND v.status='PUBLISHED' AND m.status='APPROVED'`,[mediaId,departureId]);if(!result.rowCount||!deliveryId(result.rows[0]))throw new AppError(404,'PUBLIC_MEDIA_NOT_FOUND','El archivo publicado no existe');return result.rows[0];}
async function stream(req:Request,res:Response,media:PublicMedia,disposition?:'attachment'){const remote=await getStorage().stream(deliveryId(media),req.headers.range);res.status(remote.status).setHeader('Content-Type',remote.mimeType||deliveryMime(media));res.setHeader('Content-Length',String(remote.size||deliverySize(media)));res.setHeader('Accept-Ranges','bytes');if(remote.contentRange)res.setHeader('Content-Range',remote.contentRange);if(disposition)res.setHeader('Content-Disposition',`attachment; filename*=UTF-8''${encodeURIComponent(deliveryName(media))}`);remote.stream.pipe(res);}
async function zip(res:Response,items:PublicMedia[],name:string){res.setHeader('Content-Type','application/zip');res.setHeader('Content-Disposition',`attachment; filename="${name}.zip"`);const archive=createArchive('zip',{zlib:{level:6}});archive.on('error',error=>res.destroy(error));archive.pipe(res);for(const item of items){const remote=await getStorage().stream(deliveryId(item));archive.append(remote.stream,{name:deliveryName(item)});}await archive.finalize();}

export const publicRouter=Router();
publicRouter.use((_,res,next)=>{secureHeaders(res);next();});

// Portal único de viajes: estas rutas deben ir antes del token escolar.
publicRouter.get('/departures/:code',asyncHandler(async(req,res)=>{const departure=await resolveDeparture(param(req.params.code));const result=await query(`SELECT l.id,l.event_date,l.title,d.id departure_id,d.name departure_name,d.destination departure_destination,d.type departure_type,d.name school_name,COALESCE(NULLIF(l.title,''),a.name,'General') activity_name,v.id version_id,v.version_number,v.status,(SELECT COUNT(*)::int FROM media_assets WHERE lot_version_id=v.id AND status='APPROVED') as approved_count,(SELECT json_agg(row_to_json(cover)) FROM (SELECT id, kind, status, COALESCE(delivery_name,original_name) as original_name, COALESCE(delivery_mime_type,mime_type) as mime_type, COALESCE(delivery_size_bytes,size_bytes) as size_bytes FROM media_assets WHERE lot_version_id=v.id AND status='APPROVED' ORDER BY sort_order, created_at LIMIT 3) cover) as cover_media FROM lots l JOIN departures d ON d.id=l.departure_id JOIN lot_versions v ON v.id=l.current_published_version_id AND v.status='PUBLISHED' LEFT JOIN activities a ON a.id=l.activity_id WHERE l.departure_id=$1 ORDER BY l.event_date DESC,v.created_at DESC`,[departure.id]);res.json({departure,items:result.rows});}))
publicRouter.get('/departures/:code/lots/:lotId',asyncHandler(async(req,res)=>{const departure=await resolveDeparture(param(req.params.code));const lot=await publishedDepartureLot(departure.id,idSchema.parse(param(req.params.lotId)));const media=await query(`SELECT id,kind,status,COALESCE(delivery_name,original_name) original_name,COALESCE(delivery_mime_type,mime_type) mime_type,COALESCE(delivery_size_bytes,size_bytes) size_bytes FROM media_assets WHERE lot_version_id=$1 AND status='APPROVED' ORDER BY sort_order,created_at`,[lot.version_id]);res.json({lot,media:media.rows});}));
publicRouter.get('/departures/:code/media/:mediaId/content',asyncHandler(async(req,res)=>{const departure=await resolveDeparture(param(req.params.code));await stream(req,res,await departureMedia(departure.id,idSchema.parse(param(req.params.mediaId))));}));
publicRouter.get('/departures/:code/media/:mediaId/thumbnail',asyncHandler(async(req,res)=>{const departure=await resolveDeparture(param(req.params.code));await stream(req,res,await departureMedia(departure.id,idSchema.parse(param(req.params.mediaId))));}));
publicRouter.get('/departures/:code/media/:mediaId/download',asyncHandler(async(req,res)=>{const departure=await resolveDeparture(param(req.params.code));await stream(req,res,await departureMedia(departure.id,idSchema.parse(param(req.params.mediaId))),'attachment');}));
publicRouter.post('/departures/:code/downloads/zip',asyncHandler(async(req,res)=>{const departure=await resolveDeparture(param(req.params.code));const input=z.object({mediaIds:z.array(z.string().uuid()).min(1).max(100)}).parse(req.body);await zip(res,await Promise.all(input.mediaIds.map(id=>departureMedia(departure.id,id))),departure.public_code+'-galeria');}));

publicRouter.get('/:token',asyncHandler(async(req,res)=>{const link=await resolveLink(param(req.params.token));const result=await query(`SELECT l.id,l.event_date,l.title,d.id departure_id,d.name departure_name,d.destination departure_destination,d.type departure_type,d.name school_name,COALESCE(NULLIF(l.title,''),a.name,'General') activity_name,v.id version_id,v.version_number,v.status,(SELECT COUNT(*)::int FROM media_assets WHERE lot_version_id=v.id AND status='APPROVED') as approved_count,(SELECT json_agg(row_to_json(cover)) FROM (SELECT id, kind, status, COALESCE(delivery_name,original_name) as original_name, COALESCE(delivery_mime_type,mime_type) as mime_type, COALESCE(delivery_size_bytes,size_bytes) as size_bytes FROM media_assets WHERE lot_version_id=v.id AND status='APPROVED' ORDER BY sort_order, created_at LIMIT 3) cover) as cover_media FROM lots l JOIN departures d ON d.id=l.departure_id JOIN departure_schools ds ON ds.departure_id=d.id AND ds.school_id=$1 JOIN lot_versions v ON v.id=l.current_published_version_id AND v.status='PUBLISHED' LEFT JOIN activities a ON a.id=l.activity_id ORDER BY l.event_date DESC,v.created_at DESC`,[link.school_id]);res.json({school:{id:link.school_id,name:link.school_name},items:result.rows});}))
publicRouter.get('/:token/lots/:lotId',asyncHandler(async(req,res)=>{const link=await resolveLink(param(req.params.token));const lot=await publishedLot(link.school_id,idSchema.parse(param(req.params.lotId)));const media=await query(`SELECT id,kind,status,COALESCE(delivery_name,original_name) original_name,COALESCE(delivery_mime_type,mime_type) mime_type,COALESCE(delivery_size_bytes,size_bytes) size_bytes FROM media_assets WHERE lot_version_id=$1 AND status='APPROVED' ORDER BY sort_order,created_at`,[lot.version_id]);res.json({lot,media:media.rows});}));
publicRouter.get('/:token/media/:mediaId/content',asyncHandler(async(req,res)=>{const link=await resolveLink(param(req.params.token));await stream(req,res,await publicMedia(link.school_id,idSchema.parse(param(req.params.mediaId))));}));
publicRouter.get('/:token/media/:mediaId/thumbnail',asyncHandler(async(req,res)=>{const link=await resolveLink(param(req.params.token));await stream(req,res,await publicMedia(link.school_id,idSchema.parse(param(req.params.mediaId))));}));
publicRouter.get('/:token/media/:mediaId/download',asyncHandler(async(req,res)=>{const link=await resolveLink(param(req.params.token));await stream(req,res,await publicMedia(link.school_id,idSchema.parse(param(req.params.mediaId))),'attachment');}));
publicRouter.post('/:token/downloads/zip',asyncHandler(async(req,res)=>{const link=await resolveLink(param(req.params.token));const input=z.object({mediaIds:z.array(z.string().uuid()).min(1).max(100)}).parse(req.body);await zip(res,await Promise.all(input.mediaIds.map(id=>publicMedia(link.school_id,id))),'galeria-recrear');}));
