import { Router } from 'express';
import { z } from 'zod';
import { query, transaction } from '../db.js';
import { AppError } from '../errors.js';
import { asyncHandler } from '../http.js';
import type { PermissionAction, PermissionModule } from '../auth.js';
const modules=['departures','lots','moderation','gallery','activities','schools','passengers','users','imports'] as const;
const actions=['view','create','edit','delete'] as const;
const item=z.object({module:z.enum(modules),view:z.boolean(),create:z.boolean(),edit:z.boolean(),delete:z.boolean()});
const payload=z.object({name:z.string().trim().min(2).max(100),description:z.string().trim().max(280).default(''),permissions:z.array(item)});
const toMatrix=(rows:any[])=>Object.fromEntries(modules.map(module=>{const value=rows.find(row=>row.module===module);return [module,{view:Boolean(value?.can_view),create:Boolean(value?.can_create),edit:Boolean(value?.can_edit),delete:Boolean(value?.can_delete)}];}));
async function writePermissions(client:any,roleId:string,permissions:z.infer<typeof item>[]){await client.query('DELETE FROM role_permissions WHERE role_id=$1',[roleId]);for(const p of permissions)await client.query('INSERT INTO role_permissions(role_id,module,can_view,can_create,can_edit,can_delete) VALUES($1,$2,$3,$4,$5,$6)',[roleId,p.module,p.view,p.create,p.edit,p.delete]);}
import { requireAdmin } from '../auth.js';

export const rolesRouter=Router();
rolesRouter.use(requireAdmin);
rolesRouter.get('/',asyncHandler(async(_req,res)=>{const result=await query(`SELECT r.id,r.name,r.description,r.is_system_admin AS "isSystemAdmin",r.active,COUNT(u.id)::int AS "userCount" FROM roles r LEFT JOIN users u ON u.role_id=r.id GROUP BY r.id ORDER BY r.is_system_admin DESC,r.name`);res.json({items:result.rows});}));
rolesRouter.get('/:id',asyncHandler(async(req,res)=>{const role=await query('SELECT id,name,description,is_system_admin AS "isSystemAdmin",active FROM roles WHERE id=$1',[req.params.id]);if(!role.rowCount)throw new AppError(404,'ROLE_NOT_FOUND','Rol no encontrado');const permissions=await query('SELECT module,can_view,can_create,can_edit,can_delete FROM role_permissions WHERE role_id=$1',[req.params.id]);res.json({...role.rows[0],permissions:toMatrix(permissions.rows)});}));
rolesRouter.post('/',asyncHandler(async(req,res)=>{const input=payload.parse(req.body);if(new Set(input.permissions.map(p=>p.module)).size!==input.permissions.length)throw new AppError(400,'DUPLICATE_PERMISSION_MODULE','No repitas módulos');const role=await transaction(async client=>{const created=await client.query('INSERT INTO roles(name,description) VALUES($1,$2) RETURNING id,name,description,is_system_admin AS "isSystemAdmin",active',[input.name,input.description]);await writePermissions(client,created.rows[0].id,input.permissions);return created.rows[0];});await query('INSERT INTO audit_log(actor_id,action,entity_type,entity_id,metadata) VALUES($1,$2,$3,$4,$5)',[req.user!.id,'ROLE_CREATED','role',role.id,JSON.stringify({name:role.name})]);res.status(201).json(role);}));
rolesRouter.patch('/:id',asyncHandler(async(req,res)=>{const input=payload.partial().parse(req.body);const role=await query<{isSystemAdmin:boolean}>('SELECT is_system_admin AS "isSystemAdmin" FROM roles WHERE id=$1',[req.params.id]);if(!role.rowCount)throw new AppError(404,'ROLE_NOT_FOUND','Rol no encontrado');if(role.rows[0].isSystemAdmin)throw new AppError(400,'SYSTEM_ROLE_PROTECTED','El rol Administrador no se puede modificar');await transaction(async client=>{if(input.name!==undefined||input.description!==undefined)await client.query('UPDATE roles SET name=COALESCE($1,name),description=COALESCE($2,description),updated_at=now() WHERE id=$3',[input.name??null,input.description??null,req.params.id]);if(input.permissions!==undefined)await writePermissions(client,String(req.params.id),input.permissions);});await query('INSERT INTO audit_log(actor_id,action,entity_type,entity_id) VALUES($1,$2,$3,$4)',[req.user!.id,'ROLE_UPDATED','role',req.params.id]);res.status(204).end();}));
rolesRouter.post('/:id/duplicate',asyncHandler(async(req,res)=>{const input=z.object({name:z.string().trim().min(2).max(100),description:z.string().trim().max(280).default('')}).parse(req.body);const role=await transaction(async client=>{const source=await client.query('SELECT id FROM roles WHERE id=$1',[req.params.id]);if(!source.rowCount)throw new AppError(404,'ROLE_NOT_FOUND','Rol no encontrado');const created=await client.query('INSERT INTO roles(name,description) VALUES($1,$2) RETURNING id,name,description',[input.name,input.description]);await client.query('INSERT INTO role_permissions(role_id,module,can_view,can_create,can_edit,can_delete) SELECT $1,module,can_view,can_create,can_edit,can_delete FROM role_permissions WHERE role_id=$2',[created.rows[0].id,req.params.id]);return created.rows[0];});res.status(201).json(role);}));
rolesRouter.delete('/:id',asyncHandler(async(req,res)=>{const role=await query<{isSystemAdmin:boolean;users:number}>('SELECT r.is_system_admin AS "isSystemAdmin",COUNT(u.id)::int users FROM roles r LEFT JOIN users u ON u.role_id=r.id WHERE r.id=$1 GROUP BY r.id',[req.params.id]);if(!role.rowCount)throw new AppError(404,'ROLE_NOT_FOUND','Rol no encontrado');if(role.rows[0].isSystemAdmin)throw new AppError(400,'SYSTEM_ROLE_PROTECTED','El rol Administrador no se puede eliminar');if(role.rows[0].users)throw new AppError(409,'ROLE_IN_USE','Reasigná los usuarios antes de eliminar este rol');await query('DELETE FROM roles WHERE id=$1',[req.params.id]);await query('INSERT INTO audit_log(actor_id,action,entity_type,entity_id) VALUES($1,$2,$3,$4)',[req.user!.id,'ROLE_DELETED','role',req.params.id]);res.status(204).end();}));
export {modules,actions};
