import { useEffect, useMemo, useState } from 'react';
import { ArrowLeft, Edit2, FileSpreadsheet, Plus, Search, Trash2, Upload, X, QrCode } from 'lucide-react';
import { adminRequest, api, type Passenger, type School } from '../../lib/api';
import { AdminStatusSelect } from './ConnectedViews';
import ConfirmDialog from '../ui/ConfirmDialog';
import WristbandScannerModal from './WristbandScannerModal';
import DashboardLayout from '../layout/DashboardLayout';
import { LayoutGrid, Image, Bus, School as SchoolIcon, List, Users, Upload as UploadIcon, ContactRound } from 'lucide-react';

const input: React.CSSProperties = { width:'100%', height:39, padding:'0 10px', border:'1px solid #DCE3EB', borderRadius:7, boxSizing:'border-box', font:'inherit', background:'#fff' };
const button: React.CSSProperties = { height:36, display:'inline-flex', alignItems:'center', gap:7, padding:'0 12px', border:'1px solid #DCE3EB', borderRadius:7, background:'#fff', color:'#1A4B77', fontSize:13, fontWeight:600, cursor:'pointer' };
const primary: React.CSSProperties = {...button, background:'#1A4B77', borderColor:'#1A4B77', color:'#fff'};
const emptyForm = { externalNumber:'', fullName:'', documentType:'DNI', documentNumber:'', birthDate:'', documentExpiresAt:'', country:'', passengerStatus:'', bonus:'', phone:'', mobile:'', email:'' };
type Form = typeof emptyForm;
type Preview = { valid:boolean; totalRows:number; validRows:number; errors:{row:number;field:string;message:string}[]; summary:{create:number;update:number;associate:number;rejected:number} };
const toForm = (p?:Passenger):Form => p ? {externalNumber:p.external_number??'',fullName:p.full_name,documentType:p.document_type,documentNumber:p.document_number,birthDate:p.birth_date?.slice(0,10)??'',documentExpiresAt:p.document_expires_at?.slice(0,10)??'',country:p.country??'',passengerStatus:p.passenger_status??'',bonus:p.bonus??'',phone:p.phone??'',mobile:p.mobile??'',email:p.email??''} : {...emptyForm};
const bodyOf = (f:Form) => Object.fromEntries(Object.entries(f).map(([k,v])=>[k, v.trim() || null]));
const date = (v?:string|null) => v ? v.slice(0,10).split('-').reverse().join('/') : '-';

const ADMIN_TABS = [
  { id: 'moderacion', label: 'Moderación', icon: LayoutGrid },
  { id: 'galeria', label: 'Galería', icon: Image },
  { id: 'salidas', label: 'Salidas', icon: Bus },
  { id: 'colegios', label: 'Colegios', icon: SchoolIcon },
  { id: 'actividades', label: 'Actividades', icon: List },
  { id: 'usuarios', label: 'Usuarios', icon: Users },
  { id: 'carga', label: 'Carga Manual', icon: UploadIcon },
  { id: 'pasajeros', label: 'Pasajeros', icon: ContactRound },
] as const;

export default function AdminSchoolPassengers(){
  const [school,setSchool]=useState<School|null>(null),[items,setItems]=useState<Passenger[]>([]),[search,setSearch]=useState(''),[editing,setEditing]=useState<Passenger|null>(null),[form,setForm]=useState<Form>({...emptyForm}),[open,setOpen]=useState(false),[importOpen,setImportOpen]=useState(false),[file,setFile]=useState<File|null>(null),[preview,setPreview]=useState<Preview|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[statusChange,setStatusChange]=useState<{item:Passenger;next:boolean}|null>(null),[unassignTarget,setUnassignTarget]=useState<Passenger|null>(null),[statusBusy,setStatusBusy]=useState(false),[unassignBusy,setUnassignBusy]=useState(false),[wristbandTarget,setWristbandTarget]=useState<Passenger|null>(null);
  const schoolId = useMemo(()=>{const query=new URLSearchParams(window.location.search); return query.get('schoolId') ?? '';},[]);
  const load=async()=>{if(!schoolId)return; const [schools,passengers]=await Promise.all([adminRequest<{items:School[]}>('/schools?includeInactive=true'),adminRequest<{items:Passenger[]}>(`/schools/${schoolId}/passengers?pageSize=200&q=${encodeURIComponent(search)}`)]); setSchool(schools.items.find(s=>s.id===schoolId)??null); setItems(passengers.items);};
  useEffect(()=>{void api.me().then(({user})=>{if(user.role!=='ADMIN') window.location.href='/login';}).catch(()=>window.location.href='/login');},[]);
  useEffect(()=>{void load().catch(e=>setError(e instanceof Error?e.message:'No se pudieron cargar los pasajeros.'));},[search,schoolId]);
  const save=async()=>{if(!schoolId)return;setBusy(true);setError('');try{const path=editing?`/schools/${schoolId}/passengers/${editing.id}`:`/schools/${schoolId}/passengers`;await adminRequest(path,{method:editing?'PATCH':'POST',body:JSON.stringify(bodyOf(form))});setOpen(false);setEditing(null);setForm({...emptyForm});await load();setMessage(editing?'Pasajero actualizado.':'Pasajero creado y asociado al colegio.');}catch(e){setError(e instanceof Error?e.message:'No se pudo guardar el pasajero.');}finally{setBusy(false);}};
  const previewImport=async()=>{if(!schoolId||!file)return;setBusy(true);setError('');try{const b=new FormData();b.append('file',file);setPreview(await adminRequest<Preview>(`/schools/${schoolId}/passengers/import/preview`,{method:'POST',body:b}));}catch(e){setError(e instanceof Error?e.message:'No se pudo validar el Excel.');setPreview(null);}finally{setBusy(false);}};
  const commitImport=async()=>{if(!schoolId||!file||!preview?.valid)return;setBusy(true);setError('');try{const b=new FormData();b.append('file',file);const r=await adminRequest<{created:number;updated:number;associated:number}>(`/schools/${schoolId}/passengers/import/commit`,{method:'POST',body:b});setImportOpen(false);setFile(null);setPreview(null);setMessage(`Importación completada: ${r.created} creados, ${r.updated} actualizados y ${r.associated} asociados.`);await load();}catch(e){setError(e instanceof Error?e.message:'No se pudo importar el Excel.');}finally{setBusy(false);}};
  const updateStatus=async(p:Passenger,next:boolean)=>{if(!schoolId)return;const previous=p.active;setItems(current=>current.map(value=>value.id===p.id?{...value,active:next}:value));setStatusBusy(true);setError('');try{await adminRequest('/schools/'+schoolId+'/passengers/'+p.id,{method:'PATCH',body:JSON.stringify({active:next})});setMessage(next?'Pasajero reactivado.':'Pasajero desactivado.');}catch(e){setItems(current=>current.map(value=>value.id===p.id?{...value,active:previous}:value));setError(e instanceof Error?e.message:'No se pudo actualizar el estado.');}finally{setStatusBusy(false);}};
  const unassign=async(p:Passenger)=>{if(!schoolId)return;setUnassignBusy(true);setError('');try{await adminRequest('/schools/'+schoolId+'/passengers/'+p.id,{method:'DELETE'});setUnassignTarget(null);await load();setMessage('Asociación finalizada.');}catch(e){setError(e instanceof Error?e.message:'No se pudo finalizar la asociación.');}finally{setUnassignBusy(false);}};
  if(!school)return <div style={{padding:40,color:'#64748B'}}>Cargando colegio...</div>;
  return <DashboardLayout role="admin" tabs={ADMIN_TABS as any} activeTab="colegios" onTabChange={() => { window.location.href="/admin"; }}>
    <div style={{flex:1,padding:'28px 34px',overflowY:'auto'}}>
    <div style={{display:'flex',alignItems:'center',gap:12,marginBottom:22}}><button onClick={()=>window.location.href='/admin#colegios'} style={{...button,padding:'0 10px'}} title="Volver"><ArrowLeft size={17}/></button><div><h2 style={{margin:0,color:'#1A4B77',fontSize:25}}>Pasajeros · {school.name}</h2><p style={{margin:'5px 0 0',color:'#64748B',fontSize:14}}>Colegio {school.code} · padrón asociado</p></div></div>
    <div style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:12,flexWrap:'wrap',marginBottom:18}}><div style={{position:'relative'}}><Search size={16} style={{position:'absolute',left:11,top:11,color:'#94A3B8'}}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar nombre o documento..." style={{...input,width:280,paddingLeft:34}}/></div><div style={{display:'flex',gap:9,flexWrap:'wrap'}}><button style={button} onClick={()=>{setEditing(null);setForm({...emptyForm});setOpen(true);setError('')}}><Plus size={16}/>Nuevo pasajero</button><button style={button} onClick={()=>{setImportOpen(true);setFile(null);setPreview(null);setError('')}}><Upload size={16}/>Importar Excel</button></div></div>
    {message&&<div style={{padding:'10px 12px',marginBottom:15,border:'1px solid #BBF7D0',borderRadius:8,color:'#166534',background:'#F0FDF4',fontSize:13}}>{message}</div>}{error&&!open&&!importOpen&&<div style={{padding:'10px 12px',marginBottom:15,border:'1px solid #FECACA',borderRadius:8,color:'#B91C1C',background:'#FEF2F2',fontSize:13}}>{error}</div>}
    <div style={{overflowX:'auto'}}><table style={{width:'100%',minWidth:900,borderCollapse:'collapse'}}><thead><tr style={{borderBottom:'1px solid #DCE3EB'}}>{['Pasajero','Documento','Contacto','Pulsera','Estado','Actualización','Acciones'].map(h=><th key={h} style={{padding:'11px 13px',textAlign:'left',fontSize:12,color:'#64748B',textTransform:'uppercase'}}>{h}</th>)}</tr></thead><tbody>{items.map(p=><tr key={p.id} style={{borderBottom:'1px solid #EAF0F5',opacity:p.active?1:.58}}><td style={td}><strong style={{color:'#1A4B77'}}>{p.full_name}</strong>{p.external_number&&<div style={{fontSize:12,color:'#64748B'}}>Nro. {p.external_number}</div>}</td><td style={td}>{p.document_type} {p.document_number}</td><td style={td}><div>{p.email||'-'}</div><small style={{color:'#64748B'}}>{p.mobile||p.phone||''}</small></td><td style={td}>{p.wristband_code?<span style={{display:'inline-flex',alignItems:'center',gap:4,padding:'3px 9px',background:'#DCFCE7',borderRadius:12,color:'#15803D',fontSize:12,fontWeight:700}}><QrCode size={12}/>{p.wristband_code}</span>:<span style={{color:'#94A3B8',fontSize:12}}>Sin pulsera</span>}</td><td style={td}><AdminStatusSelect active={p.active} onChange={next=>{if(!next)setStatusChange({item:p,next});else void updateStatus(p,next);}}/></td><td style={td}>{date(p.updated_at)}</td><td style={td}><button style={button} onClick={()=>{setEditing(p);setForm(toForm(p));setOpen(true);setError('')}}><Edit2 size={15}/>Editar</button><button style={{...button,color:p.wristband_code?'#15803D':'#1A4B77',marginLeft:7}} onClick={()=>setWristbandTarget(p)} title={p.wristband_code?'Gestionar pulsera':'Vincular pulsera'}><QrCode size={15}/>{p.wristband_code?'Pulsera':'Vincular'}</button><button style={{...button,color:'#B91C1C',marginLeft:7}} onClick={()=>setUnassignTarget(p)}><Trash2 size={15}/>Desasociar</button></td></tr>)}{!items.length&&<tr><td colSpan={7} style={{padding:40,textAlign:'center',color:'#94A3B8'}}>No hay pasajeros asociados a este colegio.</td></tr>}</tbody></table></div>
    {open&&<Modal title={editing?'Editar pasajero':'Nuevo pasajero'} onClose={()=>setOpen(false)}><PassengerFields form={form} setForm={setForm}/>{error&&<p style={{color:'#B91C1C',fontSize:13}}>{error}</p>}<ModalActions onCancel={()=>setOpen(false)} onSave={save} busy={busy}/></Modal>}
    {importOpen&&<Modal title="Importar pasajeros desde Excel" onClose={()=>setImportOpen(false)}><p style={{fontSize:13,color:'#64748B'}}>Los pasajeros válidos se crearán o actualizarán y quedarán asociados automáticamente a {school.code}.</p><input type="file" accept=".xlsx,.xls,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet,application/vnd.ms-excel" onChange={e=>{setFile(e.target.files?.[0]??null);setPreview(null);setError('')}} style={{...input,padding:8}}/>{file&&<p style={{fontSize:13,color:'#475569'}}><FileSpreadsheet size={15} style={{verticalAlign:'-3px',marginRight:5}}/>{file.name}</p>}{error&&<p style={{color:'#B91C1C',fontSize:13}}>{error}</p>}{preview&&<div style={{marginTop:14,padding:13,borderRadius:8,border:`1px solid ${preview.valid?'#BBF7D0':'#FECACA'}`,background:preview.valid?'#F0FDF4':'#FEF2F2'}}><strong style={{color:preview.valid?'#15803D':'#B91C1C'}}>{preview.valid?'Archivo listo':'Hay errores en el archivo'}</strong><p style={{fontSize:13}}>{preview.validRows} válidas · {preview.summary.create} nuevas · {preview.summary.update} a actualizar · {preview.summary.associate} asociaciones</p>{preview.errors.slice(0,8).map((e,i)=><div key={i} style={{fontSize:12,color:'#B91C1C'}}>Fila {e.row}: {e.field} - {e.message}</div>)}</div>}<ModalActions onCancel={()=>setImportOpen(false)} onSave={preview?.valid?commitImport:previewImport} busy={busy} disabled={!file}/></Modal>}
    <ConfirmDialog open={statusChange!==null} title="¿Pasar pasajero a Inactivo?" description="Se desactivará globalmente y conservará sus datos y asociaciones históricas." confirmLabel="Continuar" tone="danger" busy={statusBusy} onCancel={()=>!statusBusy&&setStatusChange(null)} onConfirm={async()=>{if(!statusChange)return;const change=statusChange;setStatusChange(null);await updateStatus(change.item,change.next);}}/>
    <ConfirmDialog open={unassignTarget!==null} title="¿Desasociar pasajero?" description="Se finalizará únicamente la asociación con este colegio. El pasajero seguirá en el padrón y no se modificarán sus asociaciones con otros colegios." confirmLabel="Desasociar" tone="danger" busy={unassignBusy} onCancel={()=>!unassignBusy&&setUnassignTarget(null)} onConfirm={async()=>{if(unassignTarget)await unassign(unassignTarget);}}/>
    {wristbandTarget&&<WristbandScannerModal passenger={wristbandTarget} onClose={()=>setWristbandTarget(null)} onLinked={code=>{setItems(current=>current.map(p=>p.id===wristbandTarget.id?{...p,wristband_code:code}:p));setWristbandTarget(null);}} onUnlinked={()=>{setItems(current=>current.map(p=>p.id===wristbandTarget.id?{...p,wristband_code:null}:p));setWristbandTarget(null);}}/>
    }
    </div>
  </DashboardLayout>
}
function PassengerFields({form,setForm}:{form:Form;setForm:(v:Form)=>void}){const set=(k:keyof Form,v:string)=>setForm({...form,[k]:v});const field=(label:string,k:keyof Form,type='text')=><label style={{display:'grid',gap:6,fontSize:13,color:'#334155'}}>{label}<input type={type} value={form[k]} onChange={e=>set(k,e.target.value)} style={input}/></label>;return <div style={{display:'grid',gridTemplateColumns:'repeat(2,minmax(0,1fr))',gap:12}}>{field('Nombre completo','fullName')}{field('Nro. externo','externalNumber')}{field('Tipo de documento','documentType')}{field('Número de documento','documentNumber')}{field('Fecha de nacimiento','birthDate','date')}{field('Vencimiento documento','documentExpiresAt','date')}{field('País','country')}{field('Estado','passengerStatus')}{field('Bonificación','bonus')}{field('Teléfono','phone')}{field('Celular','mobile')}{field('Correo electrónico','email')}</div>}
function ModalActions({onCancel,onSave,busy,disabled}:{onCancel:()=>void;onSave:()=>void;busy:boolean;disabled?:boolean}){return <div style={{display:'flex',justifyContent:'flex-end',gap:9,marginTop:22}}><button style={button} onClick={onCancel}>Cancelar</button><button style={{...primary,opacity:busy||disabled?.6:1}} disabled={busy||disabled} onClick={onSave}>{busy?'Procesando...':'Continuar'}</button></div>}
function Modal({title,onClose,children}:{title:string;onClose:()=>void;children:React.ReactNode}){return <div style={{position:'fixed',inset:0,zIndex:100,display:'grid',placeItems:'center',padding:18,background:'rgba(15,23,42,.48)'}}><div style={{width:'min(100%,720px)',maxHeight:'90vh',overflowY:'auto',background:'#fff',borderRadius:12,padding:25,boxShadow:'0 20px 55px rgba(0,0,0,.28)'}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginBottom:20}}><h3 style={{margin:0,color:'#1A4B77',fontSize:21}}>{title}</h3><button onClick={onClose} style={{border:0,background:'none',color:'#64748B',cursor:'pointer'}}><X size={20}/></button></div>{children}</div></div>}
const td:React.CSSProperties={padding:'13px',fontSize:13,verticalAlign:'middle'};



