import { useEffect, useMemo, useState } from 'react';
import { Edit2, FileSpreadsheet, Plus, Search, Trash2, Upload, X } from 'lucide-react';
import { adminRequest, type Passenger, type PassengerImport } from '../../lib/api';
import ConfirmDialog from '../ui/ConfirmDialog';

const input: React.CSSProperties = { width: '100%', height: 39, padding: '0 10px', border: '1px solid #E2E8F0', borderRadius: 7, boxSizing: 'border-box', font: 'inherit' };
const button: React.CSSProperties = { height: 36, display: 'inline-flex', alignItems: 'center', gap: 7, padding: '0 12px', border: '1px solid #DCE3EB', borderRadius: 7, background: '#fff', color: '#1A4B77', fontSize: 13, fontWeight: 600, cursor: 'pointer' };
const emptyForm = { externalNumber:'', fullName:'', documentType:'DNI', documentNumber:'', birthDate:'', documentExpiresAt:'', country:'', passengerStatus:'', bonus:'', phone:'', mobile:'', email:'' };
type Form = typeof emptyForm;
type Preview = { valid:boolean; totalRows:number; validRows:number; errors:{row:number;field:string;message:string}[]; summary:{create:number;update:number;rejected:number}; sample:Form[] };
const toForm = (item?: Passenger): Form => item ? { externalNumber:item.external_number??'',fullName:item.full_name,documentType:item.document_type,documentNumber:item.document_number,birthDate:item.birth_date?.slice(0,10)??'',documentExpiresAt:item.document_expires_at?.slice(0,10)??'',country:item.country??'',passengerStatus:item.passenger_status??'',bonus:item.bonus??'',phone:item.phone??'',mobile:item.mobile??'',email:item.email??'' } : emptyForm;
const asBody = (form:Form) => Object.fromEntries(Object.entries(form).map(([key,value])=>[key,value.trim() || null]));
const date = (value?:string|null) => value ? value.slice(0,10).split('-').reverse().join('/') : '-';

export default function AdminPasajeros(){
  const [items,setItems]=useState<Passenger[]>([]),[history,setHistory]=useState<PassengerImport[]>([]),[search,setSearch]=useState(''),[editing,setEditing]=useState<Passenger|null>(null),[form,setForm]=useState<Form>(emptyForm),[importOpen,setImportOpen]=useState(false),[file,setFile]=useState<File|null>(null),[preview,setPreview]=useState<Preview|null>(null),[message,setMessage]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[deactivate,setDeactivate]=useState<Passenger|null>(null);
  const load=async()=>{ const [passengers,imports]=await Promise.all([adminRequest<{items:Passenger[]}>('/passengers?pageSize=100'),adminRequest<{items:PassengerImport[]}>('/passengers/imports')]); setItems(passengers.items);setHistory(imports.items); };
  useEffect(()=>{void load();},[]);
  const visible=useMemo(()=>items.filter(item=>`${item.full_name} ${item.document_type} ${item.document_number} ${item.external_number??''}`.toLowerCase().includes(search.toLowerCase())),[items,search]);
  const save=async()=>{if(!editing)return;setBusy(true);setError('');try{await adminRequest(`/passengers/${editing.id}`,{method:'PATCH',body:JSON.stringify(asBody(form))});setEditing(null);await load();}catch(caught){setError(caught instanceof Error?caught.message:'No se pudo guardar');}finally{setBusy(false);}};
  const previewImport=async()=>{if(!file)return;setBusy(true);setError('');setMessage('');try{const body=new FormData();body.append('file',file);setPreview(await adminRequest<Preview>('/passengers/import/preview',{method:'POST',body}));}catch(caught){setError(caught instanceof Error?caught.message:'No se pudo validar el archivo');setPreview(null);}finally{setBusy(false);}};
  const commitImport=async()=>{if(!file||!preview?.valid)return;setBusy(true);setError('');try{const body=new FormData();body.append('file',file);const result=await adminRequest<{created:number;updated:number}>('/passengers/import/commit',{method:'POST',body});setMessage(`Importación completada: ${result.created} creados y ${result.updated} actualizados.`);setFile(null);setPreview(null);await load();}catch(caught){setError(caught instanceof Error?caught.message:'No se pudo importar el archivo');}finally{setBusy(false);}};
  return <div style={{flex:1,padding:32,overflowY:'auto'}}>
    <header style={{display:'flex',alignItems:'center',justifyContent:'space-between',gap:16,flexWrap:'wrap',marginBottom:24}}><div><h2 style={{margin:'0 0 5px',fontSize:24,color:'#1A4B77'}}>Pasajeros</h2><p style={{margin:0,color:'#64748B',fontSize:14}}>Padrón interno de pasajeros para futuras asignaciones a colegios y salidas.</p></div><div style={{display:'flex',gap:10,alignItems:'center',flexWrap:'wrap'}}><div style={{position:'relative'}}><Search size={16} style={{position:'absolute',left:11,top:11,color:'#94A3B8'}}/><input value={search} onChange={event=>setSearch(event.target.value)} placeholder="Buscar nombre o documento..." style={{...input,width:260,paddingLeft:34}}/></div><button onClick={()=>{setImportOpen(true);setPreview(null);setFile(null);setError('');setMessage('');}} style={button}><Upload size={16}/>Importar Excel</button></div></header>
    {message&&<div style={{padding:'11px 13px',borderRadius:8,background:'#F0FDF4',border:'1px solid #BBF7D0',color:'#15803D',fontSize:13,marginBottom:16}}>{message}</div>}
    {error&&!importOpen&&<div style={{padding:'11px 13px',borderRadius:8,background:'#FEF2F2',border:'1px solid #FECACA',color:'#B91C1C',fontSize:13,marginBottom:16}}>{error}</div>}
    <div style={{overflowX:'auto'}}><table style={{width:'100%',minWidth:900,borderCollapse:'collapse'}}><thead><tr style={{borderBottom:'1px solid #E2E8F0'}}>{['Pasajero','Documento','Contacto','Estado','Actualización','Acciones'].map(value=><th key={value} style={{padding:'12px 14px',textAlign:'left',fontSize:12,color:'#64748B',textTransform:'uppercase'}}>{value}</th>)}</tr></thead><tbody>{visible.map(item=><tr key={item.id} style={{borderBottom:'1px solid #EAF0F5',opacity:item.active?1:.58}}><td style={td}><strong style={{color:'#1A4B77'}}>{item.full_name}</strong>{item.external_number&&<div style={{fontSize:12,color:'#64748B'}}>Nro. {item.external_number}</div>}</td><td style={td}>{item.document_type} {item.document_number}</td><td style={td}><div>{item.email||'-'}</div><small style={{color:'#64748B'}}>{item.mobile||item.phone||''}</small></td><td style={td}><span style={{fontWeight:700,fontSize:12,color:item.active?'#15803D':'#B45309'}}>{item.active?'Activo':'Desactivado'}</span></td><td style={td}>{date(item.updated_at)}</td><td style={td}><button onClick={()=>{setEditing(item);setForm(toForm(item));setError('');}} style={button}><Edit2 size={15}/>Editar</button>{item.active&&<button onClick={()=>setDeactivate(item)} title="Desactivar pasajero" style={{...button,marginLeft:6,color:'#DC2626'}}><Trash2 size={15}/>Desactivar</button>}</td></tr>)}{!visible.length&&<tr><td colSpan={6} style={{padding:36,textAlign:'center',color:'#94A3B8'}}>No se encontraron pasajeros.</td></tr>}</tbody></table></div>
    {!!history.length&&<section style={{marginTop:32}}><h3 style={{fontSize:16,color:'#1A4B77',margin:'0 0 12px'}}>Últimasltimas importaciones</h3><div style={{display:'grid',gap:8}}>{history.slice(0,5).map(item=><div key={item.id} style={{display:'flex',justifyContent:'space-between',gap:12,padding:'10px 12px',border:'1px solid #E2E8F0',borderRadius:8,fontSize:13}}><span><FileSpreadsheet size={15} style={{verticalAlign:'-3px',marginRight:7,color:'#1A4B77'}}/>{item.file_name}</span><span style={{color:'#64748B'}}>{item.created_rows} nuevos · {item.updated_rows} actualizados · {date(item.created_at)} · {item.imported_by_name}</span></div>)}</div></section>}
    {editing&&<Modal title="Editar pasajero" onClose={()=>setEditing(null)}><PassengerFields form={form} setForm={setForm}/>{error&&<p style={{color:'#B91C1C',fontSize:13}}>{error}</p>}<Actions onCancel={()=>setEditing(null)} onSave={save} busy={busy}/></Modal>}
    {importOpen&&<Modal title="Importar pasajeros desde Excel" onClose={()=>setImportOpen(false)}><p style={{margin:'0 0 16px',fontSize:13,color:'#64748B'}}>Acepta archivos XLSX o XLS con las columnas del formato AV26000. Los importes, pagos y deudas no se guardan.</p><input type="file" accept=".xlsx,.xls,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet,application/vnd.ms-excel" onChange={event=>{setFile(event.target.files?.[0]??null);setPreview(null);setError('');}} style={{...input,padding:8}}/>{file&&<p style={{fontSize:13,color:'#475569'}}>{file.name}</p>}{error&&<p style={{color:'#B91C1C',fontSize:13}}>{error}</p>}{preview&&<div style={{marginTop:18,padding:14,border:'1px solid '+(preview.valid?'#BBF7D0':'#FECACA'),background:preview.valid?'#F0FDF4':'#FEF2F2',borderRadius:8}}><strong style={{color:preview.valid?'#15803D':'#B91C1C'}}>{preview.valid?'Archivo listo para importar':'Archivo con errores'}</strong><p style={{margin:'8px 0',fontSize:13}}>{preview.validRows} filas válidas · {preview.summary.create} nuevas · {preview.summary.update} a actualizar · {preview.summary.rejected} con errores</p>{preview.errors.slice(0,8).map((item,index)=><div key={index} style={{fontSize:12,color:'#B91C1C'}}>Fila {item.row}: {item.field} — {item.message}</div>)}</div>}<Actions onCancel={()=>setImportOpen(false)} onSave={preview?.valid?commitImport:previewImport} busy={busy} disabled={!file}/></Modal>}
    <ConfirmDialog open={deactivate!==null} title="¿Desactivar pasajero?" description="No se eliminará su historial y podrá reactivarse editándolo o mediante una nueva importación." confirmLabel="Desactivar" tone="danger" onCancel={()=>setDeactivate(null)} onConfirm={async()=>{if(!deactivate)return;await adminRequest(`/passengers/${deactivate.id}`,{method:'DELETE'});setDeactivate(null);await load();}}/>
  </div>;
}
function PassengerFields({form,setForm}:{form:Form;setForm:(value:Form)=>void}){const set=(key:keyof Form,value:string)=>setForm({...form,[key]:value});return <div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:13}}><Field label="Nombre y apellido"><input value={form.fullName} onChange={e=>set('fullName',e.target.value)} style={input}/></Field><Field label="Nro. externo"><input value={form.externalNumber} onChange={e=>set('externalNumber',e.target.value)} style={input}/></Field><Field label="Tipo de documento"><input value={form.documentType} onChange={e=>set('documentType',e.target.value)} style={input}/></Field><Field label="Número de documento"><input value={form.documentNumber} onChange={e=>set('documentNumber',e.target.value)} style={input}/></Field><Field label="Fecha de nacimiento"><input type="date" value={form.birthDate} onChange={e=>set('birthDate',e.target.value)} style={input}/></Field><Field label="Vencimiento documento"><input type="date" value={form.documentExpiresAt} onChange={e=>set('documentExpiresAt',e.target.value)} style={input}/></Field><Field label="País"><input value={form.country} onChange={e=>set('country',e.target.value)} style={input}/></Field><Field label="Estado"><input value={form.passengerStatus} onChange={e=>set('passengerStatus',e.target.value)} style={input}/></Field><Field label="Bonificación"><input value={form.bonus} onChange={e=>set('bonus',e.target.value)} style={input}/></Field><Field label="Teléfono"><input value={form.phone} onChange={e=>set('phone',e.target.value)} style={input}/></Field><Field label="Celular"><input value={form.mobile} onChange={e=>set('mobile',e.target.value)} style={input}/></Field><Field label="Correo electrónico"><input type="email" value={form.email} onChange={e=>set('email',e.target.value)} style={input}/></Field></div>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label style={{display:'grid',gap:7,fontSize:13,fontWeight:650,color:'#334155'}}>{label}{children}</label>}
function Actions({onCancel,onSave,busy,disabled}:{onCancel:()=>void;onSave:()=>void;busy:boolean;disabled?:boolean}){return <div style={{display:'flex',justifyContent:'flex-end',gap:9,marginTop:24}}><button onClick={onCancel} style={button}>Cancelar</button><button disabled={busy||disabled} onClick={onSave} style={{...button,background:'#1A4B77',borderColor:'#1A4B77',color:'#fff',opacity:busy||disabled?.6:1}}>{busy?'Procesando...':'Continuar'}</button></div>}
function Modal({title,onClose,children}:{title:string;onClose:()=>void;children:React.ReactNode}){return <div style={{position:'fixed',inset:0,zIndex:100,display:'grid',placeItems:'center',padding:18,background:'rgba(15,23,42,.48)'}}><div style={{width:'min(100%,700px)',maxHeight:'90vh',overflowY:'auto',borderRadius:12,background:'#fff',padding:26,boxShadow:'0 22px 60px rgba(0,0,0,.3)'}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:15,marginBottom:22}}><h3 style={{margin:0,color:'#1A4B77',fontSize:21}}>{title}</h3><button onClick={onClose} style={{border:0,background:'none',color:'#64748B',cursor:'pointer'}}><X size={20}/></button></div>{children}</div></div>}
const td:React.CSSProperties={padding:'14px',fontSize:13,verticalAlign:'middle'};



