import { useCallback, useEffect, useRef, useState } from 'react';
import { Check, Trash2, Upload, X } from 'lucide-react';
import { api, type CatalogItem, type School } from '../../lib/api';
import Lightbox from '../ui/Lightbox';
import SearchableSelect from '../ui/SearchableSelect';

type UploadFile = { id:string; file:File; preview:string; isVideo:boolean; isHeic:boolean };
const validName=/\.(jpe?g|jpe|jfif|png|heic|heif|mp4|mov)$/i;
const validTypes=new Set(['image/jpeg','image/pjpeg','image/png','image/heic','image/heif','video/mp4','video/quicktime']);
const dateInput:React.CSSProperties={width:'100%',height:44,padding:'12px 16px',border:'1px solid #E4E4E7',background:'#fff',color:'#09090B',fontSize:14,fontFamily:'inherit',outline:'none',boxSizing:'border-box',borderRadius:6};

export default function AdminCargaManual() {
  const [schools,setSchools]=useState<School[]>([]); const [activities,setActivities]=useState<CatalogItem[]>([]); const [shifts,setShifts]=useState<CatalogItem[]>([]);
  const [school,setSchool]=useState(''); const [date,setDate]=useState(new Date().toISOString().slice(0,10)); const [shift,setShift]=useState(''); const [activity,setActivity]=useState('');
  const [files,setFiles]=useState<UploadFile[]>([]); const [dragging,setDragging]=useState(false); const [uploading,setUploading]=useState(false); const [progress,setProgress]=useState(0); const [message,setMessage]=useState(''); const [selected,setSelected]=useState<string|null>(null); const input=useRef<HTMLInputElement>(null);
  useEffect(()=>{api.mySchools().then(data=>setSchools(data.items)).catch(reason=>setMessage(reason.message));},[]);
  useEffect(()=>{const selectedSchool=schools.find(item=>item.name===school); setShift('');setActivity(''); if(selectedSchool)api.catalogs(selectedSchool.id).then(data=>{setActivities(data.activities);setShifts(data.shifts);}).catch(reason=>setMessage(reason.message));},[school,schools]);
  useEffect(()=>()=>files.forEach(item=>URL.revokeObjectURL(item.preview)),[files]);
  const addFiles=(incoming:FileList|null)=>{if(!incoming)return;const accepted=Array.from(incoming).filter(file=>validName.test(file.name)||validTypes.has(file.type.toLowerCase())).map(file=>({id: Date.now().toString(36) + Math.random().toString(36).slice(2),file,preview:URL.createObjectURL(file),isVideo:file.type.startsWith('video/'),isHeic:/\.(heic|heif)$/i.test(file.name)}));setFiles(current=>[...current,...accepted]);setMessage(accepted.length===incoming.length?'':'Se omitieron archivos con formato no permitido.');};
  const drop=useCallback((event:React.DragEvent)=>{event.preventDefault();setDragging(false);addFiles(event.dataTransfer.files);},[]);
  const remove=(id:string)=>setFiles(current=>current.filter(item=>item.id!==id));
  const upload=async()=>{const schoolItem=schools.find(item=>item.name===school),activityItem=activities.find(item=>item.name===activity),shiftItem=shifts.find(item=>item.name===shift);if(!schoolItem||!activityItem||!shiftItem||!files.length)return;setUploading(true);setProgress(0);setMessage('');try{const lot=await api.createLot({schoolId:schoolItem.id,activityId:activityItem.id,shiftId:shiftItem.id,eventDate:date});for(let index=0;index<files.length;index++){await api.uploadMedia(lot.lotId,files[index].file);setProgress(Math.round((index+1)/files.length*100));}await api.submitLot(lot.lotId);setFiles([]);setMessage('Carga completada y enviada a moderación.');}catch(reason){setMessage(reason instanceof Error?reason.message:'No se pudo cargar el lote.');}finally{setUploading(false);}};
  const canUpload=Boolean(school&&date&&shift&&activity&&files.length&&!uploading); const current=files.find(item=>item.id===selected); const currentIndex=files.findIndex(item=>item.id===selected);
  return <div style={{flex:1,overflowY:'auto',padding:32}}><div style={{maxWidth:720,margin:'0 auto'}}>
    <div style={{marginBottom:32}}><h2 style={{margin:'0 0 8px',fontSize:24,color:'#1A4B77'}}>Subir material</h2><p style={{margin:0,fontSize:14,color:'#71717A'}}>Seleccioná el turno, la actividad y arrastrá las fotos.</p></div>
    <div className="responsive-grid"><SearchableSelect label="Colegio" value={school} onChange={setSchool} options={schools.map(item=>item.name)} placeholder="Seleccionar colegio..."/><label style={{display:'grid',gap:8,fontSize:13,fontWeight:500}}>Fecha<input type="date" value={date} onChange={event=>setDate(event.target.value)} style={dateInput}/></label><SearchableSelect label="Turno" value={shift} onChange={setShift} options={shifts.map(item=>item.name)} placeholder="Seleccionar turno..."/><SearchableSelect label="Actividad" value={activity} onChange={setActivity} options={activities.map(item=>item.name)} placeholder="Seleccionar actividad..."/></div>
    <div onDrop={drop} onDragOver={event=>{event.preventDefault();setDragging(true);}} onDragLeave={()=>setDragging(false)} onClick={()=>input.current?.click()} style={{border:`1px solid ${dragging?'#1A4B77':'#E4E4E7'}`,background:dragging?'#FAFAFA':'#fff',padding:'64px 24px',textAlign:'center',cursor:'pointer',transition:'all .2s ease',margin:'32px 0',borderRadius:8}}>
      <input ref={input} type="file" multiple accept=".jpg,.jpeg,.jpe,.jfif,.png,.heic,.heif,.mp4,.mov,image/jpeg,image/png,image/heic,image/heif,video/mp4,video/quicktime" hidden onChange={event=>{addFiles(event.target.files);event.currentTarget.value='';}}/>
      <Upload size={32} strokeWidth={1} color={dragging?'#1A4B77':'#A1A1AA'} style={{margin:'0 auto 16px'}}/><p style={{margin:'0 0 8px',fontWeight:500,fontSize:15,color:'#1A4B77'}}>Hacé clic o arrastrá las fotos acá</p><p style={{margin:0,fontSize:13,color:'#A1A1AA'}}>JPG, PNG, HEIC, MP4 o MOV. Se subirán en calidad original.</p>
    </div>
    {files.length>0&&<div style={{marginBottom:32}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'baseline',marginBottom:16}}><h3 style={{margin:0,fontSize:14,fontWeight:600,color:'#1A4B77'}}>Archivos seleccionados</h3><span style={{fontSize:13,color:'#71717A'}}>{files.length} archivos</span></div><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fill,minmax(80px,1fr))',gap:8,maxHeight:240,overflowY:'auto',paddingRight:8}}>{files.map(item=><div key={item.id} onClick={()=>setSelected(item.id)} style={{position:'relative',aspectRatio:'1',overflow:'hidden',background:'#F4F4F5',borderRadius:4,cursor:'pointer',transition:'transform .18s ease'}}>{item.isHeic?<div style={{height:'100%',display:'grid',placeItems:'center',fontWeight:700,color:'#64748B'}}>HEIC</div>:item.isVideo?<video src={item.preview} muted preload="metadata" style={{width:'100%',height:'100%',objectFit:'cover'}}/>:<img src={item.preview} alt="" style={{width:'100%',height:'100%',objectFit:'cover'}}/>}<button onClick={event=>{event.stopPropagation();remove(item.id);}} style={{position:'absolute',top:4,right:4,width:20,height:20,background:'rgba(0,0,0,.5)',border:0,borderRadius:'50%',cursor:'pointer',display:'grid',placeItems:'center'}}><X size={12} color="#fff"/></button></div>)}</div></div>}
    {uploading&&<div style={{marginBottom:32}}><div style={{display:'flex',justifyContent:'space-between',marginBottom:8}}><span style={{fontSize:13,color:'#1A4B77'}}>Subiendo...</span><span style={{fontSize:13,color:'#71717A'}}>{progress}%</span></div><div style={{height:4,background:'#F4F4F5',borderRadius:2,overflow:'hidden'}}><div style={{height:'100%',width:`${progress}%`,background:'#1A4B77',transition:'width .3s ease'}}/></div></div>}
    {message&&<div style={{display:'flex',alignItems:'center',gap:12,background:message.startsWith('Carga')?'#FAFAFA':'#FEF2F2',border:`1px solid ${message.startsWith('Carga')?'#E4E4E7':'#FECACA'}`,padding:16,marginBottom:32,borderRadius:8,color:message.startsWith('Carga')?'#1A4B77':'#B91C1C'}}>{message.startsWith('Carga')&&<Check size={16}/>}<span style={{fontSize:14,fontWeight:500}}>{message}</span></div>}
    <button onClick={upload} disabled={!canUpload} style={{width:'100%',padding:16,background:canUpload?'#1A4B77':'#F4F4F5',color:canUpload?'#fff':'#A1A1AA',border:0,borderRadius:8,fontSize:14,fontWeight:500,fontFamily:'inherit',cursor:canUpload?'pointer':'not-allowed',transition:'background .2s'}} onMouseEnter={event=>canUpload&&(event.currentTarget.style.background='#133656')} onMouseLeave={event=>canUpload&&(event.currentTarget.style.background='#1A4B77')}>{uploading?'Procesando...':'Subir material'}</button>
  </div>{selected&&current&&!current.isVideo&&!current.isHeic&&<Lightbox src={current.preview} onClose={()=>setSelected(null)} onNext={currentIndex<files.length-1?()=>setSelected(files[currentIndex+1].id):undefined} onPrev={currentIndex>0?()=>setSelected(files[currentIndex-1].id):undefined} actions={<button onClick={()=>{remove(current.id);setSelected(null);}} style={{background:'rgba(239,68,68,.2)',border:0,color:'#F87171',cursor:'pointer',padding:8,borderRadius:8,display:'flex',alignItems:'center',gap:8}}><Trash2 size={20}/><span style={{fontSize:13,fontWeight:500}}>Eliminar</span></button>}/>}</div>;
}

