import { useCallback, useEffect, useState } from 'react';
import { Check, Edit2, Trash2, Upload, X } from 'lucide-react';
import { api, type LotSummary } from '../../lib/api';
import PendingLotUploadModal from './PendingLotUploadModal';

const editable = (lot: LotSummary) => ['DRAFT', 'UPLOADING'].includes(lot.status);
const date = (value?: string) => value ? value.split('T')[0].split('-').reverse().join('/') : '';
const departure = (lot: LotSummary) => { const name = lot.departure_name ?? lot.school_name ?? 'Salida'; const type = lot.departure_type === 'AEREO' ? 'Aéreo' : lot.departure_type === 'MICRO' ? 'Micro' : ''; return type && !name.toLowerCase().startsWith(type.toLowerCase()) ? `${type} - ${name}` : name; };

export default function AdminEstadoCargas() {
  const [lots, setLots] = useState<LotSummary[]>([]); const [error, setError] = useState(''); const [editing, setEditing] = useState<LotSummary | null>(null); const [name, setName] = useState(''); const [busy, setBusy] = useState(false); const [deleting, setDeleting] = useState<LotSummary | null>(null); const [adding, setAdding] = useState<LotSummary | null>(null);
  const load = useCallback(async () => { try { setLots((await api.lots()).items); } catch (reason) { setError(reason instanceof Error ? reason.message : 'No se pudieron cargar los lotes.'); } }, []);
  useEffect(() => { void load(); }, [load]);
  const save = async () => { if (!editing || !name.trim()) return setEditing(null); setBusy(true); setError(''); try { await api.renameLot(editing.id, name.trim()); await load(); setEditing(null); } catch (reason) { setError(reason instanceof Error ? reason.message : 'No se pudo renombrar el álbum.'); } finally { setBusy(false); } };
  const remove = async () => { if (!deleting) return; setBusy(true); setError(''); try { await api.deleteLot(deleting.id); setLots(current => current.filter(lot => lot.id !== deleting.id)); setDeleting(null); } catch (reason) { setError(reason instanceof Error ? reason.message : 'No se pudo eliminar el lote.'); } finally { setBusy(false); } };
  return <div style={{ flex: 1, overflowY: 'auto', padding: 32 }}><div style={{ maxWidth: 1100, margin: '0 auto' }}><h2 style={{ margin: '0 0 8px', fontSize: 24, color: '#1A4B77' }}>Estado de Lotes</h2><p style={{ margin: '0 0 24px', fontSize: 14, color: '#71717A' }}>Estado de todo el material cargado en la plataforma.</p>{error && <div role="alert" style={{ color: '#B91C1C', background: '#FEF2F2', border: '1px solid #FECACA', padding: '12px 16px', borderRadius: 8, marginBottom: 24, fontSize: 13 }}>{error}</div>}
    <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}><div style={{ display: 'grid', gridTemplateColumns: '2fr 2fr 1fr 1.2fr 1fr 170px', gap: 12, padding: '12px 16px', background: '#F8FAFC', borderRadius: 8, fontSize: 12, fontWeight: 600, color: '#64748B', textTransform: 'uppercase' }}><div>Salida / Escuela</div><div>Álbum / Actividad</div><div>Fecha</div><div>Creador</div><div>Estado</div><div style={{ textAlign: 'right' }}>Acciones</div></div>
      {lots.map(lot => <div key={lot.id} style={{ display: 'grid', gridTemplateColumns: '2fr 2fr 1fr 1.2fr 1fr 170px', gap: 12, alignItems: 'center', padding: '14px 16px', background: '#fff', border: '1px solid #E2E8F0', borderRadius: 8 }}><div style={{ fontWeight: 600, color: '#1A4B77', fontSize: 14 }}>{departure(lot)}</div><div>{editing?.id === lot.id ? <div style={{ display: 'flex', gap: 6 }}><input autoFocus value={name} onChange={event => setName(event.target.value)} onKeyDown={event => { if (event.key === 'Enter') void save(); if (event.key === 'Escape') setEditing(null); }} maxLength={160} style={{ width: '100%', height: 30, padding: '0 8px', border: '1px solid #1A4B77', borderRadius: 4 }}/><button onClick={() => void save()} disabled={busy} style={icon}><Check size={14}/></button><button onClick={() => setEditing(null)} disabled={busy} style={icon}><X size={14}/></button></div> : <div style={{ display: 'flex', gap: 6, alignItems: 'center' }}><span style={{ color: '#334155', fontSize: 14 }}>{lot.album_name || lot.activity_name}</span>{editable(lot) && <button onClick={() => { setEditing(lot); setName(lot.album_name || lot.activity_name); }} title="Editar nombre del álbum" style={plain}><Edit2 size={13}/></button>}</div>}</div><div style={muted}>{date(lot.event_date)}</div><div style={muted}>{lot.created_by_name || 'Coordinador'}</div><div><Status status={lot.status}/></div><div style={{ textAlign: 'right' }}>{lot.status === 'PENDING' && <button onClick={() => setAdding(lot)} title="Añadir fotos" style={{ ...plain, color: '#1A4B77', fontWeight: 600, marginRight: 7 }}><Upload size={14}/> Añadir fotos</button>}{editable(lot) && editing?.id !== lot.id && <button onClick={() => setDeleting(lot)} title="Eliminar lote" style={{ ...plain, color: '#EF4444' }}><Trash2 size={14}/> Eliminar</button>}</div></div>)}{!lots.length && <p style={{ color: '#71717A', padding: '16px 0' }}>Todavía no hay lotes cargados.</p>}</div>
  </div>{deleting && <ConfirmDelete lot={deleting} busy={busy} onCancel={() => setDeleting(null)} onConfirm={() => void remove()}/>} {adding && <PendingLotUploadModal lot={adding} onClose={() => setAdding(null)} onComplete={() => void load()}/>}</div>;
}
function Status({ status }: { status: string }) { const pending = status === 'PENDING'; const published = status === 'PUBLISHED'; return <span style={{ display: 'inline-block', padding: '4px 10px', borderRadius: 14, background: published ? '#DCFCE7' : pending ? '#FEF3C7' : '#E2E8F0', color: published ? '#166534' : pending ? '#92400E' : '#475569', fontSize: 12, fontWeight: 600 }}>{published ? 'Publicado' : pending ? 'Pendiente' : status === 'UPLOADING' ? 'En carga' : status}</span>; }
function ConfirmDelete({ lot, busy, onCancel, onConfirm }: { lot: LotSummary; busy: boolean; onCancel: () => void; onConfirm: () => void }) { return <div style={{ position: 'fixed', inset: 0, zIndex: 200, background: 'rgba(15,23,42,.45)', display: 'grid', placeItems: 'center', padding: 16 }}><div style={{ width: 'min(100%,400px)', background: '#fff', borderRadius: 12, padding: 28 }}><h3 style={{ margin: '0 0 10px', color: '#1A4B77' }}>¿Eliminar este lote?</h3><p style={{ color: '#64748B', fontSize: 13 }}>Se eliminará “{lot.album_name || lot.activity_name}” y todos sus archivos.</p><div style={{ display: 'flex', justifyContent: 'flex-end', gap: 10 }}><button onClick={onCancel} disabled={busy} style={button}>Cancelar</button><button onClick={onConfirm} disabled={busy} style={{ ...button, background: '#EF4444', color: '#fff', border: 0 }}>{busy ? 'Eliminando…' : 'Eliminar lote'}</button></div></div></div>; }
const muted: React.CSSProperties = { color: '#64748B', fontSize: 13 }; const plain: React.CSSProperties = { border: 0, background: 'none', cursor: 'pointer', padding: 4, fontSize: 12, display: 'inline-flex', alignItems: 'center', gap: 4 }; const icon: React.CSSProperties = { width: 30, border: '1px solid #DCE3EB', background: '#fff', borderRadius: 4, cursor: 'pointer' }; const button: React.CSSProperties = { padding: '10px 18px', border: '1px solid #DCE3EB', borderRadius: 6, background: '#fff', cursor: 'pointer' };
