import { useEffect, useRef, useState } from 'react';
import { AlertCircle, Check, LoaderCircle, Upload, X } from 'lucide-react';
import { api, type LotSummary } from '../../lib/api';

type PendingFile = { id: string; file: File; preview: string; video: boolean; status: 'queued'|'uploading'|'uploaded'|'failed'; error?: string };
const validName = /\.(jpe?g|jpe|jfif|png|heic|heif|mp4|mov)$/i;
const validTypes = new Set(['image/jpeg','image/pjpeg','image/png','image/heic','image/heif','video/mp4','video/quicktime']);
// Cada archivo se procesa con marca de agua y se envía al almacenamiento remoto.
// Serializar evita saturar el procesamiento cuando se selecciona un lote grande.
const MAX_PARALLEL_UPLOADS = 1;

export default function PendingLotUploadModal({ lot, onClose, onComplete }: { lot: LotSummary; onClose: () => void; onComplete: (count: number) => void }) {
  const [files, setFiles] = useState<PendingFile[]>([]); const [dragging, setDragging] = useState(false); const [busy, setBusy] = useState(false); const [message, setMessage] = useState(''); const input = useRef<HTMLInputElement>(null); const previews = useRef<string[]>([]);
  useEffect(() => () => previews.current.forEach(URL.revokeObjectURL), []);
  const addFiles = (incoming: FileList | null) => { if (!incoming || busy) return; const raw = Array.from(incoming); const accepted = raw.filter(file => validName.test(file.name) || validTypes.has(file.type.toLowerCase())).map(file => ({ id: crypto.randomUUID(), file, preview: URL.createObjectURL(file), video: file.type.startsWith('video/') || /\.(mp4|mov)$/i.test(file.name), status: 'queued' as const })); previews.current.push(...accepted.map(item => item.preview)); setFiles(current => [...current, ...accepted]); setMessage(accepted.length === raw.length ? '' : `Se omitieron ${raw.length - accepted.length} archivo(s) con formato no permitido.`); };
  const update = (id: string, patch: Partial<PendingFile>) => setFiles(current => current.map(item => item.id === id ? { ...item, ...patch } : item));
  const submit = async () => { const pending = files.filter(item => item.status === 'queued' || item.status === 'failed'); if (!pending.length || busy) return; setBusy(true); setMessage(''); let cursor = 0; let uploaded = 0; let failed = 0; const worker = async () => { while (true) { const item = pending[cursor++]; if (!item) return; update(item.id, { status: 'uploading', error: undefined }); try { await api.uploadMedia(lot.id, item.file); update(item.id, { status: 'uploaded' }); uploaded += 1; } catch (reason) { failed += 1; update(item.id, { status: 'failed', error: reason instanceof Error ? reason.message : 'No se pudo subir.' }); } } }; await Promise.all(Array.from({ length: Math.min(MAX_PARALLEL_UPLOADS, pending.length) }, worker)); setBusy(false); if (uploaded) onComplete(uploaded); setMessage(failed ? `${uploaded} archivo(s) subido(s); ${failed} falló/fallaron. Podés reintentar los fallidos.` : `${uploaded} archivo(s) añadido(s). El álbum continúa pendiente de moderación.`); };
  return <div role="dialog" aria-modal="true" aria-label="Añadir fotos" style={{ position: 'fixed', inset: 0, zIndex: 300, background: 'rgba(15,23,42,.48)', display: 'grid', placeItems: 'center', padding: 16 }}><div style={{ width: 'min(100%,720px)', maxHeight: '90vh', overflowY: 'auto', background: '#fff', borderRadius: 12, padding: 24, boxShadow: '0 20px 50px rgba(15,23,42,.24)' }}>
    <div style={{ display: 'flex', justifyContent: 'space-between', gap: 16, alignItems: 'start' }}><div><h3 style={{ margin: 0, color: '#1A4B77', fontSize: 19 }}>Añadir fotos al álbum</h3><p style={{ margin: '6px 0 0', color: '#64748B', fontSize: 13 }}>{lot.album_name || lot.activity_name} · seguirá pendiente de moderación.</p></div><button onClick={onClose} disabled={busy} aria-label="Cerrar" style={{ border: 0, background: 'none', color: '#64748B', cursor: 'pointer' }}><X size={20}/></button></div>
    <div onClick={() => input.current?.click()} onDrop={event => { event.preventDefault(); setDragging(false); addFiles(event.dataTransfer.files); }} onDragOver={event => { event.preventDefault(); setDragging(true); }} onDragLeave={() => setDragging(false)} style={{ margin: '22px 0 16px', padding: '40px 20px', textAlign: 'center', border: `1px dashed ${dragging ? '#1A4B77' : '#94A3B8'}`, borderRadius: 8, background: dragging ? '#F8FAFC' : '#fff', cursor: busy ? 'wait' : 'pointer' }}><input ref={input} hidden multiple type="file" accept=".jpg,.jpeg,.jpe,.jfif,.png,.heic,.heif,.mp4,.mov,image/jpeg,image/png,image/heic,image/heif,video/mp4,video/quicktime" onChange={event => { addFiles(event.target.files); event.currentTarget.value = ''; }}/><Upload size={28} color="#1A4B77"/><div style={{ marginTop: 8, color: '#1A4B77', fontWeight: 600 }}>Elegí o arrastrá fotos y videos</div><small style={{ color: '#64748B' }}>JPG, PNG, HEIC, MP4 o MOV</small></div>
    {!!files.length && <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill,minmax(105px,1fr))', gap: 10, maxHeight: 270, overflowY: 'auto' }}>{files.map(item => <div key={item.id} title={item.error || item.file.name} style={{ position: 'relative', aspectRatio: '1', overflow: 'hidden', borderRadius: 7, background: '#F1F5F9', outline: item.status === 'failed' ? '2px solid #EF4444' : item.status === 'uploaded' ? '2px solid #22C55E' : 'none' }}>{item.video ? <video src={item.preview} muted style={{ width: '100%', height: '100%', objectFit: 'cover' }}/> : <img src={item.preview} alt="" style={{ width: '100%', height: '100%', objectFit: 'cover' }}/>}<span style={{ position: 'absolute', inset: 'auto 4px 4px 4px', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap', padding: '3px 5px', borderRadius: 4, background: 'rgba(15,23,42,.75)', color: '#fff', fontSize: 10 }}>{item.status === 'uploading' ? 'Subiendo…' : item.status === 'uploaded' ? 'Listo' : item.status === 'failed' ? 'Error' : item.file.name}</span>{item.status === 'uploading' && <LoaderCircle size={20} style={{ position: 'absolute', top: 8, right: 8, color: '#fff' }}/>}</div>)}</div>}
    {message && <div role="status" style={{ display: 'flex', gap: 8, marginTop: 16, padding: 11, borderRadius: 7, color: message.includes('falló') ? '#B91C1C' : '#166534', background: message.includes('falló') ? '#FEF2F2' : '#F0FDF4', fontSize: 13 }}>{message.includes('falló') ? <AlertCircle size={17}/> : <Check size={17}/>} {message}</div>}
    <div style={{ display: 'flex', justifyContent: 'flex-end', gap: 9, marginTop: 22 }}><button onClick={onClose} disabled={busy} style={{ padding: '10px 15px', border: '1px solid #DCE3EB', borderRadius: 7, background: '#fff', cursor: 'pointer' }}>Cerrar</button>{files.some(item => item.status === 'queued' || item.status === 'failed') && <button onClick={() => void submit()} disabled={busy} style={{ padding: '10px 15px', border: 0, borderRadius: 7, background: '#1A4B77', color: '#fff', cursor: busy ? 'wait' : 'pointer', opacity: busy ? .7 : 1 }}>{busy ? 'Subiendo…' : files.some(item => item.status === 'failed') ? 'Reintentar fallidos' : 'Añadir archivos'}</button>}</div>
  </div></div>;
}
