import { useEffect, useMemo, useState } from 'react';
import { Copy, Edit2, Plus, Search, Trash2 } from 'lucide-react';
import { adminRequest, type PermissionAction, type PermissionMatrix, type PermissionModule } from '../../lib/api';

const modules: PermissionModule[] = ['moderation','gallery','departures','schools','activities','users','lots','passengers'];
const labels: Record<PermissionModule,string> = { moderation:'Moderación', gallery:'Galería', departures:'Salidas', schools:'Colegios', activities:'Actividades', users:'Usuarios', lots:'Carga manual', passengers:'Pasajeros', imports:'Importaciones' };
type Role = { id:string; name:string; description:string; isSystemAdmin:boolean; active:boolean; userCount:number; permissions?:PermissionMatrix };
const empty = () => Object.fromEntries(modules.map(module => [module,{view:false,create:false,edit:false,delete:false}])) as PermissionMatrix;
const primary: React.CSSProperties = { display:'inline-flex',alignItems:'center',justifyContent:'center',gap:8,padding:'10px 16px',background:'#1A4B77',color:'#fff',border:0,borderRadius:6,fontSize:13,fontWeight:600,cursor:'pointer' };
const secondary: React.CSSProperties = { display:'inline-flex',alignItems:'center',justifyContent:'center',gap:8,padding:'10px 16px',background:'#fff',color:'#1A4B77',border:'1px solid #D7E0EA',borderRadius:6,fontSize:13,fontWeight:600,cursor:'pointer' };
const icon = (color='#64748B', disabled=false):React.CSSProperties => ({display:'inline-flex',alignItems:'center',justifyContent:'center',width:30,height:30,border:0,background:'none',cursor:disabled?'not-allowed':'pointer',color,opacity:disabled?.4:1});

export default function RolesView() {
  const [items,setItems]=useState<Role[]>([]); const [search,setSearch]=useState(''); const [open,setOpen]=useState(false); const [editing,setEditing]=useState<Role|null>(null); const [name,setName]=useState(''); const [description,setDescription]=useState(''); const [permissions,setPermissions]=useState<PermissionMatrix>(empty()); const [error,setError]=useState('');
  const load=()=>adminRequest<{items:Role[]}>('/roles').then(data=>setItems(data.items));
  useEffect(()=>{void load().catch(reason=>setError(reason instanceof Error?reason.message:'No se pudieron cargar los roles.'));},[]);
  const edit=async(role?:Role)=>{setError('');if(!role){setEditing(null);setName('');setDescription('');setPermissions(empty());setOpen(true);return;}try{const detail=await adminRequest<Role>('/roles/'+role.id);setEditing(detail);setName(detail.name);setDescription(detail.description);setPermissions(detail.permissions??empty());setOpen(true);}catch(reason){setError(reason instanceof Error?reason.message:'No se pudo abrir el rol.');}};
  const save=async()=>{try{const body={name,description,permissions:modules.map(module=>({module,...permissions[module]}))};await adminRequest('/roles'+(editing?'/'+editing.id:''),{method:editing?'PATCH':'POST',body:JSON.stringify(body)});setOpen(false);await load();}catch(reason){setError(reason instanceof Error?reason.message:'No se pudo guardar el rol.');}};
  const duplicate=async(role:Role)=>{const next=prompt('Nombre del nuevo rol',role.name+' copia');if(!next)return;try{await adminRequest('/roles/'+role.id+'/duplicate',{method:'POST',body:JSON.stringify({name:next,description:role.description})});await load();}catch(reason){setError(reason instanceof Error?reason.message:'No se pudo duplicar el rol.');}};
  const remove=async(role:Role)=>{if(!confirm(`¿Eliminar el rol ${role.name}?`))return;try{await adminRequest('/roles/'+role.id,{method:'DELETE'});await load();}catch(reason){setError(reason instanceof Error?reason.message:'No se pudo eliminar el rol.');}};
  const visible=useMemo(()=>items.filter(role=>(role.name+' '+role.description).toLowerCase().includes(search.toLowerCase())),[items,search]);
  return <div style={{flex:1,padding:32,overflowY:'auto',background:'#fff'}}>
    <header style={{display:'flex',alignItems:'center',justifyContent:'space-between',gap:16,flexWrap:'wrap',marginBottom:24}}><div><h2 style={{margin:'0 0 4px',fontSize:24,color:'#1A4B77'}}>Roles</h2><p style={{margin:0,fontSize:14,color:'#71717A'}}>Gestión de roles y permisos reutilizables.</p></div><div style={{display:'flex',gap:12,alignItems:'center',flexWrap:'wrap',flex:1,justifyContent:'flex-end',minWidth:280}}><div style={{position:'relative',flex:1,minWidth:140}}><Search size={16} style={{position:'absolute',left:12,top:11,color:'#71717A'}}/><input value={search} onChange={event=>setSearch(event.target.value)} placeholder="Buscar..." style={{height:38,width:'100%',padding:'0 12px 0 36px',border:'1px solid #E4E4E7',borderRadius:7,fontSize:13,boxSizing:'border-box'}}/></div><div style={{flexShrink:0}}><button style={primary} onClick={()=>void edit()}><Plus size={16}/>Nuevo Rol</button></div></div></header>
    {error&&<div role="alert" style={{margin:'16px 0',padding:'12px 16px',borderRadius:8,color:'#B91C1C',background:'#FEF2F2',border:'1px solid #FECACA',fontSize:13}}>{error}</div>}
    <style dangerouslySetInnerHTML={{__html: `
      @media (max-width: 768px) {
        .responsive-card-table thead { display: none; }
        .responsive-card-table, .responsive-card-table tbody, .responsive-card-table tr, .responsive-card-table td { display: block; width: 100%; box-sizing: border-box; }
        .responsive-card-table { min-width: 0 !important; }
        .responsive-card-table tr { margin-bottom: 16px; border: 1px solid #E2E8F0 !important; border-radius: 8px; padding: 12px; background: #fff; display: flex; flex-direction: column; gap: 12px; }
        .responsive-card-table td { display: flex; flex-direction: column; align-items: flex-start; padding: 0 !important; border: none !important; text-align: left; width: 100%; box-sizing: border-box; gap: 4px; word-break: break-word; }
        .responsive-card-table td::before { content: attr(data-label); font-weight: 600; font-size: 11px; color: #64748B; text-transform: uppercase; margin-bottom: 2px; }
        .responsive-card-table td:last-child { flex-direction: row; justify-content: flex-end; gap: 8px; margin-top: 8px; padding-top: 12px !important; border-top: 1px solid #F1F5F9 !important; }
        .responsive-card-table td:last-child::before { display: none; }
      }
    `}} />
    <table className="responsive-card-table" style={{width:'100%',borderCollapse:'collapse',textAlign:'left',background:'#fff'}}><thead><tr style={{borderBottom:'1px solid #E4E4E7'}}>{['Rol','Descripción','Usuarios','Acciones'].map(label=><th key={label} style={{padding:'12px 20px',textAlign:label==='Acciones'?'right':'left',fontSize:12,color:'#71717A',textTransform:'uppercase'}}>{label}</th>)}</tr></thead><tbody>{visible.map(role=><tr key={role.id} style={{borderBottom:'1px solid #E4E4E7'}}><td data-label="Rol" style={{padding:'12px 20px',fontSize:13,fontWeight:role.isSystemAdmin?700:400,color:'#1A4B77'}}>{role.name}</td><td data-label="Descripción" style={{padding:'12px 20px',fontSize:13,color:'#1A4B77'}}>{role.description||'—'}</td><td data-label="Usuarios" style={{padding:'12px 20px',fontSize:13,color:'#1A4B77'}}>{role.userCount}</td><td data-label="Acciones" style={{padding:'12px 20px',textAlign:'right'}}><div style={{display:'flex',justifyContent:'flex-end',alignItems:'center',gap:8}}><button title="Editar" aria-label="Editar" disabled={role.isSystemAdmin} onClick={()=>void edit(role)} style={icon('#64748B',role.isSystemAdmin)}><Edit2 size={16}/></button><button title="Duplicar" aria-label="Duplicar" onClick={()=>void duplicate(role)} style={icon('#1A4B77')}><Copy size={16}/></button><button title="Eliminar" aria-label="Eliminar" disabled={role.isSystemAdmin||role.userCount>0} onClick={()=>void remove(role)} style={icon('#DC2626',role.isSystemAdmin||role.userCount>0)}><Trash2 size={16}/></button></div></td></tr>)}{!visible.length&&<tr><td colSpan={4} style={{padding:32,textAlign:'center',fontSize:13,color:'#71717A'}}>No se encontraron roles.</td></tr>}</tbody></table>
    {open&&<div style={{position:'fixed',inset:0,background:'rgba(15,23,42,.45)',zIndex:50,display:'grid',placeItems:'center'}}><div style={{width:'min(820px,92vw)',maxHeight:'88vh',overflow:'auto',background:'#fff',borderRadius:12,padding:24}}><h3 style={{margin:'0 0 20px',fontSize:20,color:'#1A4B77'}}>{editing?'Editar rol':'Nuevo rol'}</h3><label style={{display:'grid',gap:7,fontSize:13,fontWeight:600}}>Nombre<input value={name} onChange={event=>setName(event.target.value)} style={{padding:'10px 12px',border:'1px solid #E4E4E7',borderRadius:6,font:'inherit',fontSize:13}}/></label><label style={{display:'grid',gap:7,fontSize:13,fontWeight:600,marginTop:12}}>Descripción<input value={description} onChange={event=>setDescription(event.target.value)} style={{padding:'10px 12px',border:'1px solid #E4E4E7',borderRadius:6,font:'inherit',fontSize:13}}/></label><table style={{width:'100%',marginTop:18,borderCollapse:'collapse'}}><thead><tr style={{borderBottom:'1px solid #E4E4E7'}}><th style={{padding:10,textAlign:'left',fontSize:12,color:'#71717A',textTransform:'uppercase'}}>Módulo</th>{(['view','create','edit','delete'] as PermissionAction[]).map(action=><th key={action} style={{padding:10,fontSize:12,color:'#71717A',textTransform:'uppercase'}}>{action==='view'?'Ver':action==='create'?'Crear':action==='edit'?'Editar':'Eliminar'}</th>)}</tr></thead><tbody>{modules.map(module=><tr key={module} style={{borderBottom:'1px solid #E4E4E7'}}><td style={{padding:10,fontSize:13,fontWeight:600,color:'#1A4B77'}}>{labels[module]}</td>{(['view','create','edit','delete'] as PermissionAction[]).map(action=><td key={action} style={{padding:10,textAlign:'center'}}><input type="checkbox" checked={permissions[module][action]} onChange={()=>setPermissions(current=>({...current,[module]:{...current[module],[action]:!current[module][action]}}))}/></td>)}</tr>)}</tbody></table><div style={{display:'flex',justifyContent:'flex-end',gap:10,marginTop:24}}><button style={secondary} onClick={()=>setOpen(false)}>Cancelar</button><button style={primary} onClick={()=>void save()}>Guardar</button></div></div></div>}
  </div>;
}
